In [137]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("new.csv")
type(data)

pandas.core.frame.DataFrame

In [138]:
data


GENERIC NAME         CONDITION              SOURCE  COUNT  \
0             minocycline              Acne           Ernakulam  987.0   
1              sertraline        Depression           Kozhikode  365.0   
2              lisinopril      Hypertension            Kasargod   54.0   
3            elvitegravir          AIDS/HIV            Palakkad   32.0   
4           triamcinolone         Hair Loss  Thiruvananthapuram   65.0   
5       lidocaine topical  Gastrointestinal      Pathanamthitta   65.0   
6           emtricitabine          AIDS/HIV             Aleppey  789.0   
7              lisinopril      Hypertension            Kasargod    5.0   
8               bupropion        Depression  Thiruvananthapuram  654.0   
9         diphenhydramine              Cold           Kozhikode  320.0   
10      minoxidil topical         Hair Loss              Kollam  654.0   
11         spironolactone              Acne  Thiruvananthapuram  500.0   
12              alvimopan  Gastrointestinal            Kottayam  741.0   
13             sertraline        Depression           Kozhikode   65.0   
14       chlorpheniramine              Cold            Kasargod  654.0   
15          triamcinolone         Hair Loss  Thiruvananthapuram  654.0   
16           elvitegravir          AIDS/HIV            Palakkad  797.0   
17      lidocaine topical  Gastrointestinal      Pathanamthitta   32.0   
18             duloxetine        Depression              Kollam   65.0   
19      minoxidil topical         Hair Loss              Kollam    6.0   
20          emtricitabine          AIDS/HIV             Aleppey  987.0   
21             lisinopril      Hypertension            Kasargod    6.0   
22      minoxidil topical         Hair Loss              Kollam  654.0   
23              bupropion        Depression  Thiruvananthapuram   32.0   
24         spironolactone              Acne  Thiruvananthapuram  125.0   
25            rizatriptan          Migraine            Palakkad  654.0   
26           elvitegravir          AIDS/HIV            Palakkad   25.0   
27              alvimopan  Gastrointestinal            Kottayam   98.0   
28       chlorpheniramine              Cold            Kasargod   32.0   
29            rizatriptan          Migraine            Palakkad   65.0   
30             sertraline        Depression           Kozhikode  321.0   
31             eletriptan          Migraine             Wayanad   54.0   
32          emtricitabine          AIDS/HIV             Aleppey  987.0   
33      lidocaine topical  Gastrointestinal      Pathanamthitta   25.0   
34       chlorpheniramine              Cold            Kasargod  321.0   
35             lisinopril      Hypertension            Kasargod  412.0   
36      tretinoin topical              Acne            Thrissur  987.0   
37              alvimopan  Gastrointestinal            Kottayam    5.0   
38        diphenhydramine              Cold           Kozhikode  546.0   
39             duloxetine        Depression              Kollam   32.0   
40            rizatriptan          Migraine            Palakkad   65.0   
41           elvitegravir          AIDS/HIV            Palakkad  587.0   
42             lisinopril      Hypertension            Kasargod    5.0   
43       chlorpheniramine              Cold            Kasargod   32.0   
44              alvimopan  Gastrointestinal            Kottayam  654.0   
45          triamcinolone         Hair Loss  Thiruvananthapuram   62.0   
46         spironolactone              Acne  Thiruvananthapuram   58.0   
47             sertraline        Depression           Kozhikode   54.0   
48             eletriptan          Migraine             Wayanad   65.0   
49           elvitegravir          AIDS/HIV            Palakkad  458.0   
50      lidocaine viscous  Gastrointestinal            Thrissur  654.0   
51        diphenhydramine              Cold           Kozhikode   32.0   
52            rizatriptan          Migraine            Palakkad  652.0   
53      minoxidil

In [139]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
#processed_data["GENERIC"] = data["GENERIC NAME"]
processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])
#processed_data["CONDITIO"] = data["CONDITION"]
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
#processed_data["src"] = data["SOURCE"]
processed_data["cnt"] = data["COUNT"]
processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])

processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
#processed_data["Mon"] = data["MONTH"]
processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [140]:
processed_data

#to display complete dataset

#pd.set_option('display.height', 2400)
#pd.set_option('display.max_rows', 2400)

GENERIC NAME  CONDITION  SOURCE    cnt  COUNT  MONTH  DESTINATION
0               15          1       1  987.0    112      3            2
1               18          3       7  365.0     68      4            3
2               13          6       4   54.0     30      2            1
3                9          0       9   32.0     20      0            4
4               22          5      11   65.0     38      2           13
5               11          4      10   65.0     38      3            4
6               10          0       0  789.0    102      4           11
7               13          6       4    5.0      2      7           12
8                1          3      11  654.0     92      4            1
9                5          2       7  320.0     58      2            9
10              16          5       5  654.0     92      4            0
11              19          1      11  500.0     76      4            5
12               0          4       6  741.0     99      2            1
13              18          3       7   65.0     38     11           13
14               2          2       4  654.0     92      4            3
15              22          5      11  654.0     92      2            5
16               9          0       9  797.0    103      4            8
17              11          4      10   32.0     20     10            4
18               7          3       5   65.0     38      2            1
19              16          5       5    6.0      3      2            4
20              10          0       0  987.0    112      3           11
21              13          6       4    6.0      3      4            1
22              16          5       5  654.0     92      3            0
23               1          3      11   32.0     20      2           12
24              19          1      11  125.0     50      4            0
25              17          7       9  654.0     92      4            3
26               9          0       9   25.0     17      9            7
27               0          4       6   98.0     46      4            1
28               2          2       4   32.0     20      2           11
29              17          7       9   65.0     38      3            3
30              18          3       7  321.0     59      3            3
31               8          7      13   54.0     30      4            5
32              10          0       0  987.0    112      7           11
33              11          4      10   25.0     17      4           13
34               2          2       4  321.0     59      3            3
35              13          6       4  412.0     70      2            3
36              21          1      12  987.0    112      4            9
37               0          4       6    5.0      2      6            2
38               5          2       7  546.0     80      4            9
39               7          3       5   32.0     20      7           12
40              17          7       9   65.0     38      7            3
41               9          0       9  587.0     85      3            8
42              13          6       4    5.0      2      2           12
43               2          2       4   32.0     20      3           11
44               0          4       6  654.0     92      3            1
45              22          5      11   62.0     36      9            5
46              19          1      11   58.0     34      3            0
47              18          3       7   54.0     30      7            3
48               8          7      13   65.0     38      3            5
49               9          0       9  458.0     73      7            8
50              12          4      12  654.0     92      4            8
51               5          2       7   32.0     20      3            9
52              17          7       9  652.0     91      0            3
53              16          5       5    5.0      2      2            3
54              15          1       1  654.0  

In [141]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'CONDITION', 'SOURCE', 'cnt', 'COUNT', 'MONTH',
       'DESTINATION'],
      dtype='object')


In [142]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'DESTINATION'

In [143]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0                   Idukki
1                   Kannur
2                Ernakulam
3                 Kasargod
4                  Wayanad
5                 Kasargod
6       Thiruvananthapuram
7                 Thrissur
8                Ernakulam
9                 Palakkad
10                 Aleppey
11                  Kollam
12               Ernakulam
13                 Wayanad
14                  Kannur
15                  Kollam
16              Malappuram
17                Kasargod
18               Ernakulam
19                Kasargod
20      Thiruvananthapuram
21               Ernakulam
22                 Aleppey
23                Thrissur
24                 Aleppey
25                  Kannur
26               Kozhikode
27               Ernakulam
28      Thiruvananthapuram
29                  Kannur
30                  Kannur
31                  Kollam
32      Thiruvananthapuram
33                 Wayanad
34                  Kannur
35                  Kannur
36                Palakkad
3

In [144]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["DESTINATION"]
prediction_class

0        2
1        3
2        1
3        4
4       13
5        4
6       11
7       12
8        1
9        9
10       0
11       5
12       1
13      13
14       3
15       5
16       8
17       4
18       1
19       4
20      11
21       1
22       0
23      12
24       0
25       3
26       7
27       1
28      11
29       3
30       3
31       5
32      11
33      13
34       3
35       3
36       9
37       2
38       9
39      12
40       3
41       8
42      12
43      11
44       1
45       5
46       0
47       3
48       5
49       8
50       8
51       9
52       3
53       3
54       2
55       1
56      12
57       9
58       5
59       3
60      13
61       5
62      11
63      10
64      13
65      11
66       2
67       3
68       3
69       0
70      11
71      13
72       5
73       0
74       9
75       1
76       9
77       2
78      12
79       8
80       3
81       1
82       2
83       9
84      13
85       5
86       9
87       5
88       2
89       0
90      12

In [145]:
features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","COUNT","MONTH"]]

#    features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]
features_data

GENERIC NAME  CONDITION  SOURCE  COUNT  MONTH
0               15          1       1    112      3
1               18          3       7     68      4
2               13          6       4     30      2
3                9          0       9     20      0
4               22          5      11     38      2
5               11          4      10     38      3
6               10          0       0    102      4
7               13          6       4      2      7
8                1          3      11     92      4
9                5          2       7     58      2
10              16          5       5     92      4
11              19          1      11     76      4
12               0          4       6     99      2
13              18          3       7     38     11
14               2          2       4     92      4
15              22          5      11     92      2
16               9          0       9    103      4
17              11          4      10     20     10
18               7          3       5     38      2
19              16          5       5      3      2
20              10          0       0    112      3
21              13          6       4      3      4
22              16          5       5     92      3
23               1          3      11     20      2
24              19          1      11     50      4
25              17          7       9     92      4
26               9          0       9     17      9
27               0          4       6     46      4
28               2          2       4     20      2
29              17          7       9     38      3
30              18          3       7     59      3
31               8          7      13     30      4
32              10          0       0    112      7
33              11          4      10     17      4
34               2          2       4     59      3
35              13          6       4     70      2
36              21          1      12    112      4
37               0          4       6      2      6
38               5          2       7     80      4
39               7          3       5     20      7
40              17          7       9     38      7
41               9          0       9     85      3
42              13          6       4      2      2
43               2          2       4     20      3
44               0          4       6     92      3
45              22          5      11     36      9
46              19          1      11     34      3
47              18          3       7     30      7
48               8          7      13     38      3
49               9          0       9     73      7
50              12          4      12     92      4
51               5          2       7     20      3
52              17          7       9     91      0
53              16          5       5      2      2
54              15          1       1     92      4
55               7          3       5     59      9
56              14          6       8     79      4
57               2          2       4     20      4
58              19          1      11     77      3
59               2          2       4     13      7
60              22          5      11     38      2
61               9          0       9      8     11
62               0          4       6     30      6
63              13          6       4      0      2
64              19          1      11     17      3
65              12          4      12     31      1
66              15          1       1    106      7
67               2          2       4     17      0
68              17          7       9     93      8
69              16          5       5     38      7
70              10          0       0    112      0
71              11          4      10      3      2
72              22          5      11     59     10
73              19          1      11     48      7
74               5          2       7     84      7
75               0          4       6     59      7
76

In [146]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(0) #to make random numbers predictable

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
#print(y_train.shape[0])
print("Testing samples")
print(X_test.shape[0])


Training samples
2414
Testing samples
604


In [147]:
X_train

GENERIC NAME  CONDITION  SOURCE  COUNT  MONTH
1754             9          0       9     84      1
2043             8          7      13     30      4
1050            22          5      11     36      9
439             12          4      12     92      1
2539            17          7       9     92      4
94              22          5      11     37      7
2367            20          7       8    112      5
1433            13          6       4     92      4
2786            16          5       5     43      7
268              7          3       5     38      2
32              10          0       0    112      7
199              3          1       0    107      4
2415            21          1      12      7      4
228             20          7       8      2      4
2246            10          0       0     68      5
1628            19          1      11     10      1
302              2          2       4     56     10
2391             5          2       7     59      9
1334             1          3      11     20      5
2679            15          1       1     26      4
134             21          1      12    107      0
1386            10          0       0     13     11
825             14          6       8     30      1
2207             0          4       6     92      5
2641            15          1       1     97     10
2836            14          6       8     30      1
1900            14          6       8     24      9
480              8          7      13      2      2
2066            15          1       1     92      4
870              3          1       0    107      1
2662            21          1      12     98      8
2557             2          2       4     20      3
2497            12          4      12     63      2
1011            10          0       0    102      4
700             17          7       9      3      3
2150            15          1       1     92      9
287             20          7       8     31      4
1678            19          1      11     95      5
501              8          7      13      6      6
119             19          1      11     10      1
364             10          0       0     20      9
2447             6          1      10    106      8
557             15          1       1     92      4
1080             0          4       6     59      7
561             19          1      11     77      3
1065            22          5      11     38      2
1597            15          1       1    106      8
1534            17          7       9     92      4
2771             8          7      13     29      2
784              3          1       0    102      7
2083            11          4      10      3      2
2292            12          4      12     38      3
1322             2          2       4     59      9
1684            16          5       5     38      5
1292            20          7       8     31      4
2469            18          3       7     38      9
573             10          0       0    112      0
2163             9          0       9     20      5
1355            11          4      10     38      8
233             14          6       8     30      8
817             11          4      10     84      5
341              8          7      13      2      2
2626            16          5       5     94      8
82              15          1       1     82      0
2792            11          4      10     46      1
188             13          6       4     84     10
1533            19          1      11     50      4
549             19          1      11     34      3
2070            19          1      11     77      3
1994            12          4      12     63      2
1772            22          5      11     94      8
959              6          1      10     47      7
1038            11          4      10     17      4
543             17          7       9     38      7
477              6          1      10    102      3
1791             0          4       6     37      5
29

In [148]:
y_train

1754     8
2043     5
1050     5
439      8
2539     3
94       4
2367    11
1433     3
2786     1
268      4
32      11
199     11
2415    13
228      1
2246    11
1628     6
302      3
2391     9
1334     1
2679     9
134      9
1386     2
825     12
2207     1
2641     2
2836    12
1900    12
480     11
2066     2
870     11
2662     9
2557    11
2497     8
1011    11
700     12
2150     2
287      5
1678     5
501      2
119      6
364      3
2447    11
557      2
1080     1
561      5
1065    13
1597     2
1534     3
2771     5
784     11
2083    13
2292     8
1322     3
1684     0
1292     5
2469    12
573     11
2163     3
1355    11
233     12
817     11
341     12
2626     0
82       2
2792    11
188      3
1533     0
549      0
2070     5
1994     8
1772     5
959      1
1038    13
543      3
477     11
1791     7
2970     1
1145     3
1459     3
397      7
954      2
654      3
1579    11
2259     1
1026     1
724     11
250      1
993      4
1239    11
1861    12
280      8

In [149]:
#applying model

#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 3)
knn


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [150]:
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)
cv_scores

array([ 0.94155844,  0.94155844,  0.94754098,  0.92131148,  0.93687708,
        0.95016611,  0.92976589,  0.9632107 ,  0.92567568,  0.92905405])

In [151]:
cv_scores.mean()

0.93867188498605392

In [152]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)

predictions_test

array([ 2, 11, 11,  2,  1,  0, 13,  1, 12, 11,  5,  1,  5,  1,  8,  7, 11,
       12,  1,  7, 13, 11,  9,  5, 11,  3,  1,  2,  9, 13,  5,  0,  5,  3,
       12,  8,  9,  9,  9,  1,  4,  3,  9,  3, 11,  3,  3,  2,  3, 11, 12,
        3,  3,  0, 12,  8, 11,  5,  2,  5,  9,  3, 13,  9,  3, 11,  1,  8,
       11,  5, 11,  3,  0,  7,  7,  3,  3,  8, 11, 11,  3,  8,  1,  5, 11,
        3, 12,  1,  1, 11,  4, 11,  3, 11,  1, 11, 13,  1,  7, 12,  1,  9,
        9,  5,  7,  2, 12,  1,  7,  5, 13,  9, 13,  3,  1,  5,  8,  5,  1,
        2,  1,  9,  3,  3, 12,  9,  9,  3,  9,  1,  3,  0,  9,  9,  7,  5,
        2,  3, 11,  9, 10,  4, 11, 11,  4, 12,  9,  0,  3, 11,  1,  4,  5,
        1, 11,  3, 10,  9,  3, 13,  5,  9,  3,  3,  3,  0,  0,  0,  2,  2,
        5,  1,  0, 13, 10,  0,  8, 11,  3,  5,  3,  1, 13,  8,  7,  7,  5,
       11, 11,  1,  0, 11, 11, 11,  5,  0, 13,  3,  9,  5,  2, 11,  9,  8,
        5,  7,  1,  2,  4, 13,  1,  5,  3, 11,  5,  9, 11,  1,  2, 12,  7,
       11, 13,  3,  9,  9

In [153]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[22  0  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0 75  0  3  2  0  0  1  0  0  0  0  0  4]
 [ 0  0 39  0  0  0  0  0  0  0  0  1  1  0]
 [ 0  0  0 85  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  4  0 16  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 55  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0 27  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 53  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0 12  0  0  2]
 [ 0  2  0  0  0  3  0  0  0  2  0 77  0  0]
 [ 0  4  0  0  0  0  0  0  0  1  0  2 36  0]
 [ 0  0  0  3  0  0  0  0  0  2  0  0  0 25]]


In [154]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 0.915562913907


In [155]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       0.93      0.88      0.90        85
           2       0.91      0.95      0.93        41
           3       0.92      0.98      0.95        87
           4       0.89      0.76      0.82        21
           5       0.83      1.00      0.91        55
           6       1.00      1.00      1.00         2
           7       0.96      0.90      0.93        30
           8       1.00      0.85      0.92        34
           9       0.88      1.00      0.94        53
          10       1.00      0.80      0.89        15
          11       0.93      0.92      0.92        84
          12       0.97      0.84      0.90        43
          13       0.81      0.83      0.82        30

   micro avg       0.92      0.92      0.92       604
   macro avg       0.93      0.90      0.91       604
weighted avg       0.92      0.92      0.92       604



In [156]:
from sklearn.naive_bayes import GaussianNB

In [157]:
#Create a Gaussian Classifier
gau = GaussianNB()

cvscores_gau = cross_val_score(gau,features_data,prediction_class,cv=10)
cvscores_gau

array([ 0.33766234,  0.31168831,  0.32459016,  0.32131148,  0.28903654,
        0.34219269,  0.30769231,  0.33110368,  0.30743243,  0.28716216])

In [158]:
cvscores_gau.mean()

0.31598721057919787

In [159]:
# Train the model using the training sets
gau.fit(X_train,y_train)

#Predict Output
prediction_gau = gau.predict(X_test) # 0:Overcast, 2:Mild

In [160]:
prediction_gau

array([11,  9,  3,  1,  1,  3,  5, 11,  1,  9,  5,  3,  5,  1,  8,  1, 11,
        3,  1,  3,  5, 11,  1,  8, 11,  0, 11,  9,  1,  5,  5,  3,  3,  3,
        3,  8,  9,  1,  1,  1, 12,  3,  9,  1, 11, 13,  1,  9,  5, 11,  1,
        0,  1,  9,  3,  8,  5,  9, 11,  5,  1,  1,  5,  9, 11, 11,  1, 13,
        8, 13,  8,  0,  0,  1, 11,  1,  3,  8, 11,  3,  2,  8,  1,  3,  3,
        1,  1,  9, 11, 13,  5, 12,  1,  8,  3,  1,  5,  5,  3,  3,  5,  1,
        9,  1,  1,  1,  1,  1,  1,  5,  3,  1, 13,  1, 13,  3,  8,  5,  1,
       11,  5,  9, 11,  1,  3,  9,  9, 11,  9,  3,  3,  9,  2,  9,  1,  5,
        1,  2,  5,  1,  3,  5, 11,  3,  1,  3,  9,  9,  1, 11,  1,  3,  9,
        3, 11, 11,  1,  9,  3,  3,  5,  1,  3, 11, 13,  3,  9,  0,  3,  5,
        5, 11, 11, 11,  1,  9,  5,  8,  3, 13,  3,  9,  1,  8,  3,  3,  1,
       11, 11, 11,  9, 11,  5,  3,  5,  0,  3, 11,  9,  3, 11,  1,  9,  8,
        5,  7,  1, 11, 11,  1, 11,  5,  3,  9,  9,  9,  8,  1, 11,  3,  1,
        1,  1,  1,  9,  1

In [161]:
print(confusion_matrix(y_test,prediction_gau))

[[ 3  2  0 10  0  0  0  0  0  8  0  1  0  0]
 [ 0 28  0 12  0 18  0  0  0  4  0 17  3  3]
 [ 0 11  2  6  0  1  0  2  0  3  0 15  1  0]
 [ 4 31  4 22  0  6  0  0  0  4  0 12  0  4]
 [ 0  6  0  3  0  3  0  1  2  0  0  3  2  1]
 [ 0  5  0  7  0 28  0  0  0 10  0  2  0  3]
 [ 0  0  1  0  0  0  0  0  0  0  0  0  0  1]
 [ 0 14  0  7  0  4  0  3  1  0  0  1  0  0]
 [ 0  0  0  0  0  2  0  0 29  2  0  0  0  1]
 [ 0 17  3  0  0  0  0  1  1 30  0  1  0  0]
 [ 0  5  0  4  0  5  0  0  0  0  0  0  0  1]
 [ 0 15  0 18  0  4  0  0 12 10  0 24  0  1]
 [ 0 17  0 24  0  2  0  0  0  0  0  0  0  0]
 [ 0  7  0  9  0  6  0  0  0  2  0  1  0  5]]


In [162]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,prediction_gau))

Accuracy is 0.288079470199


In [163]:
print(classification_report(y_test,prediction_gau))

              precision    recall  f1-score   support

           0       0.43      0.12      0.19        24
           1       0.18      0.33      0.23        85
           2       0.20      0.05      0.08        41
           3       0.18      0.25      0.21        87
           4       0.00      0.00      0.00        21
           5       0.35      0.51      0.42        55
           6       0.00      0.00      0.00         2
           7       0.43      0.10      0.16        30
           8       0.64      0.85      0.73        34
           9       0.41      0.57      0.48        53
          10       0.00      0.00      0.00        15
          11       0.31      0.29      0.30        84
          12       0.00      0.00      0.00        43
          13       0.25      0.17      0.20        30

   micro avg       0.29      0.29      0.29       604
   macro avg       0.24      0.23      0.21       604
weighted avg       0.26      0.29      0.26       604



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [164]:
from sklearn import tree

dec = tree.DecisionTreeClassifier()

dec


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [165]:
cv_scores_dec = cross_val_score(dec,features_data,prediction_class,cv=10)
cv_scores_dec

array([ 0.92207792,  0.91883117,  0.93114754,  0.90819672,  0.92358804,
        0.92358804,  0.91638796,  0.93311037,  0.90878378,  0.92567568])

In [166]:
cv_scores_dec.mean()

0.92113872201570479

In [167]:
dec.fit(X_train, y_train)

prediction_dec = dec.predict(X_test)
prediction_dec

array([ 2, 11, 11,  2,  1,  0, 13,  1, 12, 11,  5,  1,  5,  1,  8,  7, 11,
       12,  1,  7, 13, 11,  9,  8, 11,  3,  1,  2,  1, 13,  5,  0,  5,  3,
       12,  8,  9, 12,  9,  1,  4,  3,  9,  3, 11,  3,  3,  2,  3, 11, 12,
        3,  3,  0, 12,  8, 11,  5,  2,  5,  9,  3, 13,  9,  3, 11,  1,  8,
       11,  5, 11,  3,  0,  7,  7,  3,  3,  8, 11, 11,  3,  8,  1,  5, 11,
        3, 12,  1,  1,  4,  4, 11,  1, 11,  1, 11, 13,  1,  7, 12,  1, 12,
        9,  5,  7,  2, 12,  1,  7,  5, 13,  9, 13,  3,  1,  5,  8,  5,  1,
        2,  1,  9,  3,  3, 12,  9,  9,  3,  9,  1,  3,  0,  9,  9,  7,  5,
        2,  3, 11, 13, 10,  4, 11, 11, 13, 12,  9,  0,  3, 11,  1,  4,  5,
        1, 11,  3, 10,  9,  3, 13,  5, 13,  3,  3,  3,  0,  0,  0,  2,  2,
        5,  1,  0, 13, 10,  0,  8, 11,  3,  5,  3,  1, 13,  8,  7,  7,  5,
       11, 11,  1,  0, 11, 11, 11,  5,  0, 13,  3,  9,  5,  2, 11,  9,  8,
        5,  7,  1,  2,  4, 13,  1,  5,  3, 11,  5,  9, 11,  1,  2, 12,  7,
       12, 13,  3,  9, 12

In [168]:
from sklearn.metrics import accuracy_score

#confusion matrix

print(confusion_matrix(y_test,prediction_dec))

[[22  2  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 79  0  0  0  0  0  0  0  0  0  0  0  6]
 [ 0  0 39  0  0  0  0  0  0  0  0  1  1  0]
 [ 0  3  0 82  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  4  0 16  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0 55  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  3  0 26  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 34  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 48  0  0  3  2]
 [ 0  0  0  1  0  0  0  0  0  0 12  0  0  2]
 [ 0  2  0  0  1  3  0  0  0  0  0 74  4  0]
 [ 0  4  0  0  0  0  0  0  0  0  0  2 37  0]
 [ 0  0  0  3  0  0  0  0  0  1  0  0  0 26]]


In [169]:
#accuracy

print("Accuracy is " ,metrics.accuracy_score(y_test,prediction_dec))

Accuracy is  0.913907284768


In [170]:
#giving input 
new=pd.DataFrame([[15,1,1,112,3]])
new

0  1  2    3  4
0  15  1  1  112  3

In [171]:
pre_out_knn = knn.predict(new)

In [172]:
print(pre_out_knn)

[2]


In [173]:
pre_out_gau = gau.predict(new)

In [174]:
print(pre_out_gau)

[11]


In [175]:
pre_out_dec = dec.predict(new)

In [176]:
print(pre_out_dec)

[2]
