In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("withoutcondition.csv")
type(data)

pandas.core.frame.DataFrame

In [3]:
data

GENERIC NAME              SOURCE  COUNT      MONTH  \
0           minocycline           Ernakulam  987.0   February   
1            sertraline           Kozhikode  365.0    January   
2            lisinopril            Kasargod   54.0   December   
3          elvitegravir            Palakkad   32.0      April   
4         triamcinolone  Thiruvananthapuram   65.0   December   
5     lidocaine topical      Pathanamthitta   65.0   February   
6         emtricitabine             Aleppey  789.0    January   
7            lisinopril            Kasargod    5.0      March   
8             bupropion  Thiruvananthapuram  654.0    January   
9       diphenhydramine           Kozhikode  320.0   December   
10    minoxidil topical              Kollam  654.0    January   
11       spironolactone  Thiruvananthapuram  500.0    January   
12            alvimopan            Kottayam  741.0   December   
13           sertraline           Kozhikode   65.0  September   
14     chlorpheniramine            Kasargod  654.0    January   
15        triamcinolone  Thiruvananthapuram  654.0   December   
16         elvitegravir            Palakkad  797.0    January   
17    lidocaine topical      Pathanamthitta   32.0    October   
18           duloxetine              Kollam   65.0   December   
19    minoxidil topical              Kollam    6.0   December   
20        emtricitabine             Aleppey  987.0   February   
21           lisinopril            Kasargod    6.0    January   
22    minoxidil topical              Kollam  654.0   February   
23            bupropion  Thiruvananthapuram   32.0   December   
24       spironolactone  Thiruvananthapuram  125.0    January   
25          rizatriptan            Palakkad  654.0    January   
26         elvitegravir            Palakkad   25.0   November   
27            alvimopan            Kottayam   98.0    January   
28     chlorpheniramine            Kasargod   32.0   December   
29          rizatriptan            Palakkad   65.0   February   
...                 ...                 ...    ...        ...   
2988          darunavir            Thrissur   21.0   February   
2989         sertraline           Kozhikode   65.0   December   
2990  lidocaine viscous            Thrissur   77.0    January   
2991        doxycycline      Pathanamthitta  789.0   February   
2992        sumatriptan          Malappuram  987.0   February   
2993      emtricitabine             Aleppey   21.0    January   
2994         eletriptan             Wayanad    5.0   December   
2995   chlorpheniramine            Kasargod   34.0       July   
2996        doxycycline      Pathanamthitta  658.0     August   
2997  lidocaine viscous            Thrissur   65.0   December   
2998    diphenhydramine           Kozhikode   32.0    January   
2999  lidocaine viscous            Thrissur  340.0   December   
3000          darunavir            Thrissur   21.0    January   
3001         lisinopril            Kasargod  645.0   February   
3002          bupropion  Thiruvananthapuram   52.0   December   
3003        sumatriptan          Malappuram    5.0  September   
3004          darunavir            Thrissur   32.0       June   
3005  lidocaine viscous            Thrissur  972.0   November   
3006    diphenhydramine           Kozhikode   32.0   December   
3007          bupropion  Thiruvananthapuram   65.0       July   
3008        doxycycline      Pathanamthitta   45.0  September   
3009         lisinopril            Kasargod   31.0   November   
3010    diphenhydramine           Kozhikode   32.0    January   
3011          bupropion  Thiruvananthapuram   64.0      March   
3012        doxycycline      Pathanamthitta   12.0    January   
3013  lidocaine viscous            Thrissur  621.0    October   
3014          darunavir            Thrissur   32.0   December   
3015         eletriptan             Wayanad   10.0       June   
3016         lisinopril              Idukki  645.0   February   
3017    diphenhydramine              Kannur   

In [4]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
#processed_data["GENERIC"] = data["GENERIC NAME"]
#processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])
#processed_data["CONDITIO"] = data["CONDITION"]
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
#processed_data["src"] = data["SOURCE"]
#processed_data["cnt"] = data["COUNT"]
processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])

processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
#processed_data["Mon"] = data["MONTH"]
processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [5]:
processed_data

GENERIC NAME  SOURCE  COUNT  MONTH  DESTINATION
0               15       1    112      3            2
1               18       7     68      4            3
2               13       4     30      2            1
3                9       9     20      0            4
4               22      11     38      2           13
5               11      10     38      3            4
6               10       0    102      4           11
7               13       4      2      7           12
8                1      11     92      4            1
9                5       7     58      2            9
10              16       5     92      4            0
11              19      11     76      4            5
12               0       6     99      2            1
13              18       7     38     11           13
14               2       4     92      4            3
15              22      11     92      2            5
16               9       9    103      4            8
17              11      10     20     10            4
18               7       5     38      2            1
19              16       5      3      2            4
20              10       0    112      3           11
21              13       4      3      4            1
22              16       5     92      3            0
23               1      11     20      2           12
24              19      11     50      4            0
25              17       9     92      4            3
26               9       9     17      9            7
27               0       6     46      4            1
28               2       4     20      2           11
29              17       9     38      3            3
...            ...     ...    ...    ...          ...
2988             4      12     13      3            7
2989            18       7     38      2           12
2990            12      12     44      4            9
2991             6      10    102      3           11
2992            20       8    112      3           11
2993            10       0     13      4            1
2994             8      13      2      2           11
2995             2       4     21      5            3
2996             6      10     95      1           11
2997            12      12     38      2            9
2998             5       7     20      4           11
2999            12      12     63      2            8
3000             4      12     13      4            7
3001            13       4     88      3            3
3002             1      11     29      2            7
3003            20       8      2     11            3
3004             4      12     20      6            4
3005            12      12    109      9            8
3006             5       7     20      2            0
3007             1      11     38      5            4
3008             6      10     26     11            3
3009            13       4     19      9           11
3010             5       7     20      4            5
3011             1      11     37      7            3
3012             6      10      8      4            4
3013            12      12     87     10            8
3014             4      12     20      2            2
3015             8      13      6      6            2
3016            13       2     88      3            3
3017             5       3     20      2            0

[3018 rows x 5 columns]

In [6]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'SOURCE', 'COUNT', 'MONTH', 'DESTINATION'], dtype='object')


In [7]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'DESTINATION'

In [8]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0                   Idukki
1                   Kannur
2                Ernakulam
3                 Kasargod
4                  Wayanad
5                 Kasargod
6       Thiruvananthapuram
7                 Thrissur
8                Ernakulam
9                 Palakkad
10                 Aleppey
11                  Kollam
12               Ernakulam
13                 Wayanad
14                  Kannur
15                  Kollam
16              Malappuram
17                Kasargod
18               Ernakulam
19                Kasargod
20      Thiruvananthapuram
21               Ernakulam
22                 Aleppey
23                Thrissur
24                 Aleppey
25                  Kannur
26               Kozhikode
27               Ernakulam
28      Thiruvananthapuram
29                  Kannur
               ...        
2988             Kozhikode
2989              Thrissur
2990              Palakkad
2991    Thiruvananthapuram
2992    Thiruvananthapuram
2993             Ernakulam
2

In [9]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["DESTINATION"]
prediction_class

0        2
1        3
2        1
3        4
4       13
5        4
6       11
7       12
8        1
9        9
10       0
11       5
12       1
13      13
14       3
15       5
16       8
17       4
18       1
19       4
20      11
21       1
22       0
23      12
24       0
25       3
26       7
27       1
28      11
29       3
        ..
2988     7
2989    12
2990     9
2991    11
2992    11
2993     1
2994    11
2995     3
2996    11
2997     9
2998    11
2999     8
3000     7
3001     3
3002     7
3003     3
3004     4
3005     8
3006     0
3007     4
3008     3
3009    11
3010     5
3011     3
3012     4
3013     8
3014     2
3015     2
3016     3
3017     0
Name: DESTINATION, Length: 3018, dtype: int64

In [10]:
features_data = processed_data[["GENERIC NAME","SOURCE","COUNT","MONTH"]]

features_data

GENERIC NAME  SOURCE  COUNT  MONTH
0               15       1    112      3
1               18       7     68      4
2               13       4     30      2
3                9       9     20      0
4               22      11     38      2
5               11      10     38      3
6               10       0    102      4
7               13       4      2      7
8                1      11     92      4
9                5       7     58      2
10              16       5     92      4
11              19      11     76      4
12               0       6     99      2
13              18       7     38     11
14               2       4     92      4
15              22      11     92      2
16               9       9    103      4
17              11      10     20     10
18               7       5     38      2
19              16       5      3      2
20              10       0    112      3
21              13       4      3      4
22              16       5     92      3
23               1      11     20      2
24              19      11     50      4
25              17       9     92      4
26               9       9     17      9
27               0       6     46      4
28               2       4     20      2
29              17       9     38      3
...            ...     ...    ...    ...
2988             4      12     13      3
2989            18       7     38      2
2990            12      12     44      4
2991             6      10    102      3
2992            20       8    112      3
2993            10       0     13      4
2994             8      13      2      2
2995             2       4     21      5
2996             6      10     95      1
2997            12      12     38      2
2998             5       7     20      4
2999            12      12     63      2
3000             4      12     13      4
3001            13       4     88      3
3002             1      11     29      2
3003            20       8      2     11
3004             4      12     20      6
3005            12      12    109      9
3006             5       7     20      2
3007             1      11     38      5
3008             6      10     26     11
3009            13       4     19      9
3010             5       7     20      4
3011             1      11     37      7
3012             6      10      8      4
3013            12      12     87     10
3014             4      12     20      2
3015             8      13      6      6
3016            13       2     88      3
3017             5       3     20      2

[3018 rows x 4 columns]

In [11]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(0) #to make random numbers predictable

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
#print(y_train.shape[0])
print("Testing samples")
print(X_test.shape[0])

Training samples
2414
Testing samples
604


In [12]:
X_train

GENERIC NAME  SOURCE  COUNT  MONTH
1754             9       9     84      1
2043             8      13     30      4
1050            22      11     36      9
439             12      12     92      1
2539            17       9     92      4
94              22      11     37      7
2367            20       8    112      5
1433            13       4     92      4
2786            16       5     43      7
268              7       5     38      2
32              10       0    112      7
199              3       0    107      4
2415            21      12      7      4
228             20       8      2      4
2246            10       0     68      5
1628            19      11     10      1
302              2       4     56     10
2391             5       7     59      9
1334             1      11     20      5
2679            15       1     26      4
134             21      12    107      0
1386            10       0     13     11
825             14       8     30      1
2207             0       6     92      5
2641            15       1     97     10
2836            14       8     30      1
1900            14       8     24      9
480              8      13      2      2
2066            15       1     92      4
870              3       0    107      1
...            ...     ...    ...    ...
1031             9       9     17      9
2025            18       7     38     11
2189            14       8     38      0
1110             2       4     59      8
1888             5       7     59      9
1527             7       5     38      2
753              0       6     57     10
2628            11      10      3      5
562              2       4     13      7
2446            18       7     38      1
668             15       1     26      4
252             16       5     81     10
2955            14       8     79      2
2516            13       4     30      2
2962            10       0     38      7
357              8      13      3      3
1278             0       6      3      4
1300            18       7     65      5
1202            17       9      3      3
2556            13       4      2      2
2797            16       5     38      9
129             19      11     26      0
144             19      11    100      8
960             18       7     38      9
2895            10       0     13     11
2763             5       7     20      0
905             14       8      3      5
1096             8      13    112      0
235              0       6      3      2
1061            14       8     79      4

[2414 rows x 4 columns]

In [13]:
y_train

1754     8
2043     5
1050     5
439      8
2539     3
94       4
2367    11
1433     3
2786     1
268      4
32      11
199     11
2415    13
228      1
2246    11
1628     6
302      3
2391     9
1334     1
2679     9
134      9
1386     2
825     12
2207     1
2641     2
2836    12
1900    12
480     11
2066     2
870     11
        ..
1031     7
2025    13
2189    12
1110     3
1888     9
1527     1
753      1
2628     3
562      3
2446    12
668      9
252      0
2955    12
2516     1
2962     1
357      1
1278     3
1300     3
1202    12
2556    12
2797     0
129      3
144      5
960     12
2895     2
2763     3
905     11
1096     5
235      3
1061    12
Name: DESTINATION, Length: 2414, dtype: int64

In [14]:
#applying model

#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 3)
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [15]:
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)
cv_scores

array([ 0.94155844,  0.94155844,  0.94754098,  0.92131148,  0.93687708,
        0.95016611,  0.92976589,  0.9632107 ,  0.92567568,  0.92905405])

In [16]:
cv_scores.mean()

0.93867188498605392

In [17]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)

predictions_test

array([ 2, 11, 11,  2,  1,  0, 13,  1, 12, 11,  5,  1,  5,  1,  8,  7, 11,
       12,  1,  7, 13, 11,  9,  5, 11,  3,  1,  2,  9, 13,  5,  0,  5,  3,
       12,  8,  9,  9,  9,  1,  4,  3,  9,  3, 11,  3,  3,  2,  3, 11, 12,
        3,  3,  0, 12,  8, 11,  5,  2,  5,  9,  3, 13,  9,  3, 11,  1,  8,
       11,  5, 11,  3,  0,  7,  7,  3,  3,  8, 11, 11,  3,  8,  1,  5, 11,
        3, 12,  1,  1, 11,  4, 11,  3, 11,  1, 11, 13,  1,  7, 12,  1,  9,
        9,  5,  7,  2, 12,  1,  7,  5, 13,  9, 13,  3,  1,  5,  8,  5,  1,
        2,  1,  9,  3,  3, 12,  9,  9,  3,  9,  1,  3,  0,  9,  9,  7,  5,
        2,  3, 11,  9, 10,  4, 11, 11,  4, 12,  9,  0,  3, 11,  1,  4,  5,
        1, 11,  3, 10,  9,  3, 13,  5,  9,  3,  3,  3,  0,  0,  0,  2,  2,
        5,  1,  0, 13, 10,  0,  8, 11,  3,  5,  3,  1, 13,  8,  7,  7,  5,
       11, 11,  1,  0, 11, 11, 11,  5,  0, 13,  3,  9,  5,  2, 11,  9,  8,
        5,  7,  1,  2,  4, 13,  1,  5,  3, 11,  5,  9, 11,  1,  2, 12,  7,
       11, 13,  3,  9,  9

In [18]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[22  0  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0 75  0  3  2  0  0  1  0  0  0  0  0  4]
 [ 0  0 39  0  0  0  0  0  0  0  0  1  1  0]
 [ 0  0  0 85  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  4  0 16  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 55  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0 27  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 53  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0 12  0  0  2]
 [ 0  2  0  0  0  3  0  0  0  2  0 77  0  0]
 [ 0  4  0  0  0  0  0  0  0  1  0  2 36  0]
 [ 0  0  0  3  0  0  0  0  0  2  0  0  0 25]]


In [19]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 0.915562913907


In [20]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       0.93      0.88      0.90        85
           2       0.91      0.95      0.93        41
           3       0.92      0.98      0.95        87
           4       0.89      0.76      0.82        21
           5       0.83      1.00      0.91        55
           6       1.00      1.00      1.00         2
           7       0.96      0.90      0.93        30
           8       1.00      0.85      0.92        34
           9       0.88      1.00      0.94        53
          10       1.00      0.80      0.89        15
          11       0.93      0.92      0.92        84
          12       0.97      0.84      0.90        43
          13       0.81      0.83      0.82        30

   micro avg       0.92      0.92      0.92       604
   macro avg       0.93      0.90      0.91       604
weighted avg       0.92      0.92      0.92       604



In [21]:
from sklearn.naive_bayes import GaussianNB

In [22]:
#Create a Gaussian Classifier
gau = GaussianNB()

cvscores_gau = cross_val_score(gau,features_data,prediction_class,cv=10)
cvscores_gau

array([ 0.27922078,  0.27272727,  0.2852459 ,  0.27540984,  0.25913621,
        0.28903654,  0.26421405,  0.29765886,  0.26689189,  0.26351351])

In [23]:
cvscores_gau.mean()

0.27530548622324552

In [24]:
# Train the model using the training sets
gau.fit(X_train,y_train)

#Predict Output
prediction_gau = gau.predict(X_test) # 0:Overcast, 2:Mild

In [25]:
prediction_gau

array([11, 11,  3,  1,  3,  3,  5, 11,  1,  9,  5,  3,  5,  1,  8,  1, 11,
        3,  1, 13,  5, 11,  1,  8, 11,  0, 11,  5,  1,  5,  1,  3,  3,  3,
        3,  8,  5,  1,  1,  1,  8,  3,  1,  1, 11,  5,  1,  5,  5, 11,  3,
        0,  1,  5,  3,  8,  5,  5, 11, 13,  3,  1,  5,  5, 11, 11,  1, 13,
        8, 13,  8,  0, 11,  1, 11,  1,  3,  8, 11,  3,  2,  8,  1,  3,  3,
        1,  1,  9, 11,  1,  5,  3,  1,  8,  3,  1,  5,  1,  3,  3,  1,  1,
        9,  1,  8,  1,  1,  1,  1,  9,  3,  1,  5,  1,  3,  3,  8,  5,  3,
       11,  1,  1, 11,  1,  3,  5,  5, 11,  9,  3,  3,  5,  2,  5,  1,  1,
        1,  2,  1,  1,  3,  5, 11,  3,  1,  3,  5,  5,  1, 11,  1,  3,  5,
        3, 11, 11,  1,  5, 11,  3,  8,  1,  3, 11, 13,  3,  5, 11,  3,  7,
        5, 11, 11, 11,  1,  5,  1,  8,  3, 13,  3,  9,  1,  8,  3, 13,  1,
       11, 11, 11,  5, 11,  1,  3,  5, 11,  3, 11,  5,  3, 11,  1,  9,  8,
        5,  1,  1, 11, 11,  1, 11,  8,  3,  9,  5,  1,  8,  1, 11,  3,  1,
        1,  1,  1,  9,  1

In [26]:
print(confusion_matrix(y_test,prediction_gau))

[[ 0  2  0 10  0  8  0  0  0  0  0  4  0  0]
 [ 0 31  0 22  0 10  0  0  0  2  0 17  0  3]
 [ 0 12  2  8  0  3  0  1  0  0  0 15  0  0]
 [ 4 31  4 21  0  9  0  0  0  2  0 13  0  3]
 [ 0  8  0  3  0  3  0  0  4  0  0  3  0  0]
 [ 0  9  0  7  0 22  0  0  6  1  0  2  0  8]
 [ 0  0  1  0  0  1  0  0  0  0  0  0  0  0]
 [ 0 13  0  3  0  4  0  0  2  0  0  1  0  7]
 [ 0  2  0  0  0  0  0  0 31  0  0  0  0  1]
 [ 0 20  3  3  0 18  0  0  1  6  0  2  0  0]
 [ 0  5  0  4  0  2  0  0  0  0  0  0  0  4]
 [ 0 13  0 18  0  4  0  0 15  5  0 29  0  0]
 [ 0 19  0 19  0  0  0  0  0  0  0  4  0  1]
 [ 0  7  0  9  0 11  0  0  0  0  0  1  0  2]]


In [27]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,prediction_gau))

Accuracy is 0.238410596026


In [28]:
print(classification_report(y_test,prediction_gau))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        24
           1       0.18      0.36      0.24        85
           2       0.20      0.05      0.08        41
           3       0.17      0.24      0.20        87
           4       0.00      0.00      0.00        21
           5       0.23      0.40      0.29        55
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00        30
           8       0.53      0.91      0.67        34
           9       0.38      0.11      0.17        53
          10       0.00      0.00      0.00        15
          11       0.32      0.35      0.33        84
          12       0.00      0.00      0.00        43
          13       0.07      0.07      0.07        30

   micro avg       0.24      0.24      0.24       604
   macro avg       0.15      0.18      0.15       604
weighted avg       0.19      0.24      0.20       604



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [29]:
from sklearn import tree

dec = tree.DecisionTreeClassifier()

dec


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [30]:
cv_scores_dec = cross_val_score(dec,features_data,prediction_class,cv=10)
cv_scores_dec

array([ 0.92207792,  0.91883117,  0.93114754,  0.90819672,  0.92358804,
        0.92358804,  0.91638796,  0.93311037,  0.90878378,  0.92567568])

In [31]:
cv_scores_dec.mean()

0.92113872201570479

In [32]:
dec.fit(X_train, y_train)

prediction_dec = dec.predict(X_test)
prediction_dec

array([ 2, 11, 11,  2,  1,  0, 13,  1, 12, 11,  5,  1,  5,  1,  8,  7, 11,
       12,  1,  7, 13, 11,  9,  8, 11,  3,  1,  2, 12, 13,  5,  0,  5,  3,
       12,  8,  9, 12,  9,  1,  4,  3,  9,  3, 11,  3,  3,  2,  3, 11, 12,
        3,  3,  0, 12,  8, 11,  5,  2,  5,  9,  3, 13,  9,  3, 11,  1,  8,
       11,  5, 11,  3,  0,  7,  7,  3,  3,  8, 11, 11,  3,  8,  1,  5, 11,
        3, 12,  1,  1,  4,  4, 11,  1, 11,  1, 11, 13,  1,  7, 12,  1, 12,
        9,  5,  7,  2, 12,  1,  7,  5, 13,  9, 13,  3,  1,  5,  8,  5,  1,
        2,  1,  9,  3,  3, 12,  9,  9,  3,  9,  1,  3,  0,  9,  9,  7,  5,
        2,  3, 11, 13, 10,  4, 11, 11, 13, 12,  9,  0,  3, 11,  1,  4,  5,
        1, 11,  3, 10,  9,  3, 13,  5, 13,  3,  3,  3,  0,  0,  0,  2,  2,
        5,  1,  0, 13, 10,  0,  8, 11,  3,  5,  3,  1, 13,  8,  7,  7,  5,
       11, 11,  1,  0, 11, 11, 11,  5,  0, 13,  3,  9,  5,  2, 11,  9,  8,
        5,  7,  1,  2,  4, 13,  1,  5,  3, 11,  5,  9, 11,  1,  2, 12,  7,
       12, 13,  3,  9, 12

In [33]:
from sklearn.metrics import accuracy_score

#confusion matrix

print(confusion_matrix(y_test,prediction_dec))

[[22  0  0  0  0  0  0  0  0  0  0  0  2  0]
 [ 0 79  0  0  0  0  0  0  0  0  0  0  0  6]
 [ 0  0 39  0  0  0  0  0  0  0  0  1  1  0]
 [ 0  3  0 82  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  4  0 16  0  0  0  0  0  0  0  0  1]
 [ 0  0  0  0  0 55  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  1  0  0  0  3  0 26  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 34  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 48  0  0  3  2]
 [ 0  0  0  1  0  0  0  0  0  0 12  0  0  2]
 [ 0  2  0  0  1  3  0  0  0  0  0 74  4  0]
 [ 0  4  0  0  0  0  0  0  0  0  0  2 37  0]
 [ 0  0  0  3  0  0  0  0  0  1  0  0  0 26]]


In [34]:
#accuracy

print("Accuracy is " ,metrics.accuracy_score(y_test,prediction_dec))

Accuracy is  0.913907284768


In [40]:
#giving input 
new=pd.DataFrame([[15,1,112,3]])
new

0  1    2  3
0  15  1  112  3

In [41]:
test=knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(test)

2

In [42]:
pre_out_knn =arr[int(test)]

In [43]:
print(pre_out_knn)

Idukki


In [44]:
testg=gau.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(testg)

11

In [45]:
pre_out_gau = arr[int(testg)]

In [46]:
print(pre_out_gau)

Thiruvananthapuram


In [47]:
testd=knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(testd)

2

In [48]:
#pre_out_dec = dec.predict(new)
pre_out_dec = arr[int(testd)]

In [49]:
print(pre_out_dec)

Idukki
