In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("new.csv")
type(data)
#v1="minocycline"
#v2="Acne"
v3="Ernakulam"
v4=987.0
v5="February"

In [23]:
data

GENERIC NAME         CONDITION              SOURCE  COUNT  \
0           minocycline              Acne           Ernakulam  987.0   
1            sertraline        Depression           Kozhikode  365.0   
2            lisinopril      Hypertension            Kasargod   54.0   
3          elvitegravir          AIDS/HIV            Palakkad   32.0   
4         triamcinolone         Hair Loss  Thiruvananthapuram   65.0   
5     lidocaine topical  Gastrointestinal      Pathanamthitta   65.0   
6         emtricitabine          AIDS/HIV             Aleppey  789.0   
7            lisinopril      Hypertension            Kasargod    5.0   
8             bupropion        Depression  Thiruvananthapuram  654.0   
9       diphenhydramine              Cold           Kozhikode  320.0   
10    minoxidil topical         Hair Loss              Kollam  654.0   
11       spironolactone              Acne  Thiruvananthapuram  500.0   
12            alvimopan  Gastrointestinal            Kottayam  741.0   
13           sertraline        Depression           Kozhikode   65.0   
14     chlorpheniramine              Cold            Kasargod  654.0   
15        triamcinolone         Hair Loss  Thiruvananthapuram  654.0   
16         elvitegravir          AIDS/HIV            Palakkad  797.0   
17    lidocaine topical  Gastrointestinal      Pathanamthitta   32.0   
18           duloxetine        Depression              Kollam   65.0   
19    minoxidil topical         Hair Loss              Kollam    6.0   
20        emtricitabine          AIDS/HIV             Aleppey  987.0   
21           lisinopril      Hypertension            Kasargod    6.0   
22    minoxidil topical         Hair Loss              Kollam  654.0   
23            bupropion        Depression  Thiruvananthapuram   32.0   
24       spironolactone              Acne  Thiruvananthapuram  125.0   
25          rizatriptan          Migraine            Palakkad  654.0   
26         elvitegravir          AIDS/HIV            Palakkad   25.0   
27            alvimopan  Gastrointestinal            Kottayam   98.0   
28     chlorpheniramine              Cold            Kasargod   32.0   
29          rizatriptan          Migraine            Palakkad   65.0   
...                 ...               ...                 ...    ...   
2988          darunavir          AIDS/HIV            Thrissur   21.0   
2989         sertraline        Depression           Kozhikode   65.0   
2990  lidocaine viscous  Gastrointestinal            Thrissur   77.0   
2991        doxycycline              Acne      Pathanamthitta  789.0   
2992        sumatriptan          Migraine          Malappuram  987.0   
2993      emtricitabine          AIDS/HIV             Aleppey   21.0   
2994         eletriptan          Migraine             Wayanad    5.0   
2995   chlorpheniramine              Cold            Kasargod   34.0   
2996        doxycycline              Acne      Pathanamthitta  658.0   
2997  lidocaine viscous  Gastrointestinal            Thrissur   65.0   
2998    diphenhydramine              Cold           Kozhikode   32.0   
2999  lidocaine viscous  Gastrointestinal            Thrissur  340.0   
3000          darunavir          AIDS/HIV            Thrissur   21.0   
3001         lisinopril      Hypertension            Kasargod  645.0   
3002          bupropion        Depression  Thiruvananthapuram   52.0   
3003        sumatriptan          Migraine          Malappuram    5.0   
3004          darunavir          AIDS/HIV            Thrissur   32.0   
3005  lidocaine viscous  Gastrointestinal            Thrissur  972.0   
3006    diphenhydramine              Cold           Kozhikode   32.0   
3007          bupropion        Depression  Thiruvananthapuram   65.0   
3008        doxycycline              Acne      Pathanamthitta   45.0   
3009         lisinopril      Hypertension            Kasargod   31.0   
3010    diphenhydramine              Cold           Kozhikode   32.0   
3011          bupropion        Depression  Thiruvan

In [5]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
#processed_data["GENERIC"] = data["GENERIC NAME"]
processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])
#processed_data["CONDITIO"] = data["CONDITION"]
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
#processed_data["src"] = data["SOURCE"]
processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])
#processed_data["cnt"] = data["COUNT"]
processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
#processed_data["Mon"] = data["MONTH"]
processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [6]:
processed_data

GENERIC NAME  CONDITION  SOURCE  COUNT  MONTH  DESTINATION
0               15          1       1    112      3            2
1               18          3       7     68      4            3
2               13          6       4     30      2            1
3                9          0       9     20      0            4
4               22          5      11     38      2           13
5               11          4      10     38      3            4
6               10          0       0    102      4           11
7               13          6       4      2      7           12
8                1          3      11     92      4            1
9                5          2       7     58      2            9
10              16          5       5     92      4            0
11              19          1      11     76      4            5
12               0          4       6     99      2            1
13              18          3       7     38     11           13
14               2          2       4     92      4            3
15              22          5      11     92      2            5
16               9          0       9    103      4            8
17              11          4      10     20     10            4
18               7          3       5     38      2            1
19              16          5       5      3      2            4
20              10          0       0    112      3           11
21              13          6       4      3      4            1
22              16          5       5     92      3            0
23               1          3      11     20      2           12
24              19          1      11     50      4            0
25              17          7       9     92      4            3
26               9          0       9     17      9            7
27               0          4       6     46      4            1
28               2          2       4     20      2           11
29              17          7       9     38      3            3
...            ...        ...     ...    ...    ...          ...
2988             4          0      12     13      3            7
2989            18          3       7     38      2           12
2990            12          4      12     44      4            9
2991             6          1      10    102      3           11
2992            20          7       8    112      3           11
2993            10          0       0     13      4            1
2994             8          7      13      2      2           11
2995             2          2       4     21      5            3
2996             6          1      10     95      1           11
2997            12          4      12     38      2            9
2998             5          2       7     20      4           11
2999            12          4      12     63      2            8
3000             4          0      12     13      4            7
3001            13          6       4     88      3            3
3002             1          3      11     29      2            7
3003            20          7       8      2     11            3
3004             4          0      12     20      6            4
3005            12          4      12    109      9            8
3006             5          2       7     20      2            0
3007             1          3      11     38      5            4
3008             6          1      10     26     11            3
3009            13          6       4     19      9           11
3010             5          2       7     20      4            5
3011             1          3      11     37      7            3
3012             6          1      10      8      4            4
3013            12          4      12     87     10            8
3014             4          0      12     20      2            2
3015             8          7      13      6      6            2
3016            13          6       2     88      3            3
3017             5          2       3    

In [7]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'CONDITION', 'SOURCE', 'COUNT', 'MONTH', 'DESTINATION'], dtype='object')


In [8]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'DESTINATION'

In [9]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0                   Idukki
1                   Kannur
2                Ernakulam
3                 Kasargod
4                  Wayanad
5                 Kasargod
6       Thiruvananthapuram
7                 Thrissur
8                Ernakulam
9                 Palakkad
10                 Aleppey
11                  Kollam
12               Ernakulam
13                 Wayanad
14                  Kannur
15                  Kollam
16              Malappuram
17                Kasargod
18               Ernakulam
19                Kasargod
20      Thiruvananthapuram
21               Ernakulam
22                 Aleppey
23                Thrissur
24                 Aleppey
25                  Kannur
26               Kozhikode
27               Ernakulam
28      Thiruvananthapuram
29                  Kannur
               ...        
2988             Kozhikode
2989              Thrissur
2990              Palakkad
2991    Thiruvananthapuram
2992    Thiruvananthapuram
2993             Ernakulam
2

In [10]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["DESTINATION"]
prediction_class

0        2
1        3
2        1
3        4
4       13
5        4
6       11
7       12
8        1
9        9
10       0
11       5
12       1
13      13
14       3
15       5
16       8
17       4
18       1
19       4
20      11
21       1
22       0
23      12
24       0
25       3
26       7
27       1
28      11
29       3
        ..
2988     7
2989    12
2990     9
2991    11
2992    11
2993     1
2994    11
2995     3
2996    11
2997     9
2998    11
2999     8
3000     7
3001     3
3002     7
3003     3
3004     4
3005     8
3006     0
3007     4
3008     3
3009    11
3010     5
3011     3
3012     4
3013     8
3014     2
3015     2
3016     3
3017     0
Name: DESTINATION, Length: 3018, dtype: int64

In [11]:
features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","COUNT","MONTH"]]

#    features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]
features_data

GENERIC NAME  CONDITION  SOURCE  COUNT  MONTH
0               15          1       1    112      3
1               18          3       7     68      4
2               13          6       4     30      2
3                9          0       9     20      0
4               22          5      11     38      2
5               11          4      10     38      3
6               10          0       0    102      4
7               13          6       4      2      7
8                1          3      11     92      4
9                5          2       7     58      2
10              16          5       5     92      4
11              19          1      11     76      4
12               0          4       6     99      2
13              18          3       7     38     11
14               2          2       4     92      4
15              22          5      11     92      2
16               9          0       9    103      4
17              11          4      10     20     10
18               7          3       5     38      2
19              16          5       5      3      2
20              10          0       0    112      3
21              13          6       4      3      4
22              16          5       5     92      3
23               1          3      11     20      2
24              19          1      11     50      4
25              17          7       9     92      4
26               9          0       9     17      9
27               0          4       6     46      4
28               2          2       4     20      2
29              17          7       9     38      3
...            ...        ...     ...    ...    ...
2988             4          0      12     13      3
2989            18          3       7     38      2
2990            12          4      12     44      4
2991             6          1      10    102      3
2992            20          7       8    112      3
2993            10          0       0     13      4
2994             8          7      13      2      2
2995             2          2       4     21      5
2996             6          1      10     95      1
2997            12          4      12     38      2
2998             5          2       7     20      4
2999            12          4      12     63      2
3000             4          0      12     13      4
3001            13          6       4     88      3
3002             1          3      11     29      2
3003            20          7       8      2     11
3004             4          0      12     20      6
3005            12          4      12    109      9
3006             5          2       7     20      2
3007             1          3      11     38      5
3008             6          1      10     26     11
3009            13          6       4     19      9
3010             5          2       7     20      4
3011             1          3      11     37      7
3012             6          1      10      8      4
3013            12          4      12     87     10
3014             4          0      12     20      2
3015             8          7      13      6      6
3016            13          6       2     88      3
3017             5          2       3     20      2

[3018 rows x 5 columns]

In [12]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(1234)

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
print("Testing samples")
print(X_test.shape[0])


Training samples
2414
Testing samples
604


In [13]:
X_train

GENERIC NAME  CONDITION  SOURCE  COUNT  MONTH
1754             9          0       9     84      1
2043             8          7      13     30      4
1050            22          5      11     36      9
439             12          4      12     92      1
2539            17          7       9     92      4
94              22          5      11     37      7
2367            20          7       8    112      5
1433            13          6       4     92      4
2786            16          5       5     43      7
268              7          3       5     38      2
32              10          0       0    112      7
199              3          1       0    107      4
2415            21          1      12      7      4
228             20          7       8      2      4
2246            10          0       0     68      5
1628            19          1      11     10      1
302              2          2       4     56     10
2391             5          2       7     59      9
1334             1          3      11     20      5
2679            15          1       1     26      4
134             21          1      12    107      0
1386            10          0       0     13     11
825             14          6       8     30      1
2207             0          4       6     92      5
2641            15          1       1     97     10
2836            14          6       8     30      1
1900            14          6       8     24      9
480              8          7      13      2      2
2066            15          1       1     92      4
870              3          1       0    107      1
...            ...        ...     ...    ...    ...
1031             9          0       9     17      9
2025            18          3       7     38     11
2189            14          6       8     38      0
1110             2          2       4     59      8
1888             5          2       7     59      9
1527             7          3       5     38      2
753              0          4       6     57     10
2628            11          4      10      3      5
562              2          2       4     13      7
2446            18          3       7     38      1
668             15          1       1     26      4
252             16          5       5     81     10
2955            14          6       8     79      2
2516            13          6       4     30      2
2962            10          0       0     38      7
357              8          7      13      3      3
1278             0          4       6      3      4
1300            18          3       7     65      5
1202            17          7       9      3      3
2556            13          6       4      2      2
2797            16          5       5     38      9
129             19          1      11     26      0
144             19          1      11    100      8
960             18          3       7     38      9
2895            10          0       0     13     11
2763             5          2       7     20      0
905             14          6       8      3      5
1096             8          7      13    112      0
235              0          4       6      3      2
1061            14          6       8     79      4

[2414 rows x 5 columns]

In [14]:
y_train

1754     8
2043     5
1050     5
439      8
2539     3
94       4
2367    11
1433     3
2786     1
268      4
32      11
199     11
2415    13
228      1
2246    11
1628     6
302      3
2391     9
1334     1
2679     9
134      9
1386     2
825     12
2207     1
2641     2
2836    12
1900    12
480     11
2066     2
870     11
        ..
1031     7
2025    13
2189    12
1110     3
1888     9
1527     1
753      1
2628     3
562      3
2446    12
668      9
252      0
2955    12
2516     1
2962     1
357      1
1278     3
1300     3
1202    12
2556    12
2797     0
129      3
144      5
960     12
2895     2
2763     3
905     11
1096     5
235      3
1061    12
Name: DESTINATION, Length: 2414, dtype: int64

In [15]:
#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 3)
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)

cv_scores.mean()


0.93867188498605392

In [16]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[22  0  0  0  0  0  0  0  0  2  0  0  0  0]
 [ 0 75  0  3  2  0  0  1  0  0  0  0  0  4]
 [ 0  0 39  0  0  0  0  0  0  0  0  1  1  0]
 [ 0  0  0 85  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  4  0 16  0  0  0  0  0  0  1  0  0]
 [ 0  0  0  0  0 55  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  3  0 27  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0 29  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 53  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0  0 12  0  0  2]
 [ 0  2  0  0  0  3  0  0  0  2  0 77  0  0]
 [ 0  4  0  0  0  0  0  0  0  1  0  2 36  0]
 [ 0  0  0  3  0  0  0  0  0  2  0  0  0 25]]


In [17]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 0.915562913907


In [18]:

print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       1.00      0.92      0.96        24
           1       0.93      0.88      0.90        85
           2       0.91      0.95      0.93        41
           3       0.92      0.98      0.95        87
           4       0.89      0.76      0.82        21
           5       0.83      1.00      0.91        55
           6       1.00      1.00      1.00         2
           7       0.96      0.90      0.93        30
           8       1.00      0.85      0.92        34
           9       0.88      1.00      0.94        53
          10       1.00      0.80      0.89        15
          11       0.93      0.92      0.92        84
          12       0.97      0.84      0.90        43
          13       0.81      0.83      0.82        30

   micro avg       0.92      0.92      0.92       604
   macro avg       0.93      0.90      0.91       604
weighted avg       0.92      0.92      0.92       604



In [19]:
#giving input 
new=pd.DataFrame([[15,1,1,112,3]])
new

0  1   2    3  4
0  10  1  12  987  5

In [20]:
pre_out = knn.predict(new)

In [21]:
print(pre_out)

[2]
