In [418]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("dataset_emedcom.csv")
type(data)

pandas.core.frame.DataFrame

In [419]:
data

GENERIC NAME              SOURCE      MONTH         DESTINATION
0           minocycline           Ernakulam   February              Idukki
1            sertraline           Kozhikode    January              Kannur
2            lisinopril            Kasargod   December           Ernakulam
3          elvitegravir            Palakkad      April            Kasargod
4         triamcinolone  Thiruvananthapuram   December             Wayanad
5     lidocaine topical      Pathanamthitta   February            Kasargod
6         emtricitabine             Aleppey    January  Thiruvananthapuram
7       diphenhydramine           Kozhikode   December            Palakkad
8             bupropion  Thiruvananthapuram    January           Ernakulam
9        spironolactone  Thiruvananthapuram   November              Kollam
10           sertraline              Idukki      March             Aleppey
11        triamcinolone              Kannur        May            Kottayam
12    lidocaine topical              Kollam     August           Kozhikode
13        emtricitabine            Kottayam       June          Malappuram
14        triamcinolone          Malappuram  September      Pathanamthitta
15          minocycline            Thrissur       July            Thrissur
16    lidocaine topical             Wayanad    October  Thiruvananthapuram
17          minocycline           Ernakulam   February              Idukki
18           sertraline           Kozhikode    January              Kannur
19           lisinopril            Kasargod   December           Ernakulam
20         elvitegravir            Palakkad      April            Kasargod
21        triamcinolone  Thiruvananthapuram   December             Wayanad
22    lidocaine topical      Pathanamthitta   February            Kasargod
23        emtricitabine             Aleppey    January  Thiruvananthapuram
24      diphenhydramine           Kozhikode   December            Palakkad
25            bupropion  Thiruvananthapuram    January           Ernakulam
26       spironolactone  Thiruvananthapuram   November              Kollam
27           sertraline              Idukki      March             Aleppey
28        triamcinolone              Kannur        May            Kottayam
29    lidocaine topical              Kollam     August           Kozhikode
...                 ...                 ...        ...                 ...
984         minocycline            Thrissur       July            Thrissur
985   lidocaine topical             Wayanad    October  Thiruvananthapuram
986         minocycline           Ernakulam   February              Idukki
987          sertraline           Kozhikode    January              Kannur
988          lisinopril            Kasargod   December           Ernakulam
989        elvitegravir            Palakkad      April            Kasargod
990       triamcinolone  Thiruvananthapuram   December             Wayanad
991   lidocaine topical      Pathanamthitta   February            Kasargod
992       emtricitabine             Aleppey    January  Thiruvananthapuram
993     diphenhydramine           Kozhikode   December            Palakkad
994           bupropion  Thiruvananthapuram    January           Ernakulam
995      spironolactone  Thiruvananthapuram   November              Kollam
996          sertraline              Idukki      March             Aleppey
997       triamcinolone              Kannur        May            Kottayam
998   lidocaine topical              Kollam     August           Kozhikode
999       emtricitabine            Kottayam       June          Malappuram
1000      triamcinolone          Malappuram  September      Pathanamthitta
1001        minocycline            Thrissur       July            Thrissur
1002  lidocaine topical             Wayanad    October  Thiruvananthapuram
1003        minocycline           Ernakulam   February              Idukki
1004         sertraline           Kozhikode    January              Kannur
1005         lisinopril            K

In [420]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])

#processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])
#processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])

#processed_data["GENERIC"] = data["GENERIC NAME"]

#processed_data["CONDITIO"] = data["CONDITION"]
#processed_data["src"] = data["SOURCE"]
#processed_data["cnt"] = data["COUNT"]
#processed_data["Mon"] = data["MONTH"]
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [421]:
processed_data


#pd.set_option('display.height', 2400)
#pd.set_option('display.max_rows', 2400)

GENERIC NAME  SOURCE  MONTH  DESTINATION
0                6       1      3            2
1                7       7      4            3
2                5       4      2            1
3                2       9      0            4
4                9      11      2           13
5                4      10      3            4
6                3       0      4           11
7                1       7      2            9
8                0      11      4            1
9                8      11      9            5
10               7       2      7            0
11               9       3      8            6
12               4       5      1            7
13               3       6      6            8
14               9       8     11           10
15               6      12      5           12
16               4      13     10           11
17               6       1      3            2
18               7       7      4            3
19               5       4      2            1
20               2       9      0            4
21               9      11      2           13
22               4      10      3            4
23               3       0      4           11
24               1       7      2            9
25               0      11      4            1
26               8      11      9            5
27               7       2      7            0
28               9       3      8            6
29               4       5      1            7
...            ...     ...    ...          ...
984              6      12      5           12
985              4      13     10           11
986              6       1      3            2
987              7       7      4            3
988              5       4      2            1
989              2       9      0            4
990              9      11      2           13
991              4      10      3            4
992              3       0      4           11
993              1       7      2            9
994              0      11      4            1
995              8      11      9            5
996              7       2      7            0
997              9       3      8            6
998              4       5      1            7
999              3       6      6            8
1000             9       8     11           10
1001             6      12      5           12
1002             4      13     10           11
1003             6       1      3            2
1004             7       7      4            3
1005             5       4      2            1
1006             2       9      0            4
1007             9      11      2           13
1008             4      10      3            4
1009             3       0      4           11
1010             1       7      2            9
1011             0      11      4            1
1012             8      11      9            5
1013             7       2      7            0

[1014 rows x 4 columns]

In [422]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'SOURCE', 'MONTH', 'DESTINATION'], dtype='object')


In [423]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'DESTINATION'

In [424]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0                   Idukki
1                   Kannur
2                Ernakulam
3                 Kasargod
4                  Wayanad
5                 Kasargod
6       Thiruvananthapuram
7                 Palakkad
8                Ernakulam
9                   Kollam
10                 Aleppey
11                Kottayam
12               Kozhikode
13              Malappuram
14          Pathanamthitta
15                Thrissur
16      Thiruvananthapuram
17                  Idukki
18                  Kannur
19               Ernakulam
20                Kasargod
21                 Wayanad
22                Kasargod
23      Thiruvananthapuram
24                Palakkad
25               Ernakulam
26                  Kollam
27                 Aleppey
28                Kottayam
29               Kozhikode
               ...        
984               Thrissur
985     Thiruvananthapuram
986                 Idukki
987                 Kannur
988              Ernakulam
989               Kasargod
9

In [425]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["DESTINATION"]
prediction_class

0        2
1        3
2        1
3        4
4       13
5        4
6       11
7        9
8        1
9        5
10       0
11       6
12       7
13       8
14      10
15      12
16      11
17       2
18       3
19       1
20       4
21      13
22       4
23      11
24       9
25       1
26       5
27       0
28       6
29       7
        ..
984     12
985     11
986      2
987      3
988      1
989      4
990     13
991      4
992     11
993      9
994      1
995      5
996      0
997      6
998      7
999      8
1000    10
1001    12
1002    11
1003     2
1004     3
1005     1
1006     4
1007    13
1008     4
1009    11
1010     9
1011     1
1012     5
1013     0
Name: DESTINATION, Length: 1014, dtype: int64

In [426]:
features_data = processed_data[["GENERIC NAME","SOURCE","MONTH"]]

#    features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]
features_data

GENERIC NAME  SOURCE  MONTH
0                6       1      3
1                7       7      4
2                5       4      2
3                2       9      0
4                9      11      2
5                4      10      3
6                3       0      4
7                1       7      2
8                0      11      4
9                8      11      9
10               7       2      7
11               9       3      8
12               4       5      1
13               3       6      6
14               9       8     11
15               6      12      5
16               4      13     10
17               6       1      3
18               7       7      4
19               5       4      2
20               2       9      0
21               9      11      2
22               4      10      3
23               3       0      4
24               1       7      2
25               0      11      4
26               8      11      9
27               7       2      7
28               9       3      8
29               4       5      1
...            ...     ...    ...
984              6      12      5
985              4      13     10
986              6       1      3
987              7       7      4
988              5       4      2
989              2       9      0
990              9      11      2
991              4      10      3
992              3       0      4
993              1       7      2
994              0      11      4
995              8      11      9
996              7       2      7
997              9       3      8
998              4       5      1
999              3       6      6
1000             9       8     11
1001             6      12      5
1002             4      13     10
1003             6       1      3
1004             7       7      4
1005             5       4      2
1006             2       9      0
1007             9      11      2
1008             4      10      3
1009             3       0      4
1010             1       7      2
1011             0      11      4
1012             8      11      9
1013             7       2      7

[1014 rows x 3 columns]

In [427]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(0) #to make random numbers predictable

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
#print(y_train.shape[0])
print("Testing samples")
print(X_test.shape[0])


Training samples
811
Testing samples
203


In [428]:
X_train

GENERIC NAME  SOURCE  MONTH
479              2       9      0
47               3       6      6
529              5       4      2
647              7       7      4
19               5       4      2
725              9       3      8
783              7       7      4
341              7       7      4
686              3       0      4
679              4      13     10
629              6       1      3
592              9       8     11
836              2       9      0
932              9       8     11
364              1       7      2
177              1       7      2
644              6      12      5
60               8      11      9
788              3       0      4
913              4       5      1
304              6      12      5
922              9      11      2
673              7       2      7
773              0      11      4
107              4      10      3
759              9       3      8
1002             4      13     10
587              8      11      9
819              2       9      0
99               9       8     11
...            ...     ...    ...
398              1       7      2
925              1       7      2
668              4      10      3
490              9       8     11
252              9       8     11
907              3       0      4
468              8      11      9
914              3       6      6
357              6       1      3
254              4      13     10
276              9      11      2
178              0      11      4
281              8      11      9
390              4      13     10
508              6      12      5
749              7       7      4
583              4      10      3
972              2       9      0
129              7       2      7
144              0      11      4
960              0      11      4
847              9       8     11
645              4      13     10
715              7       7      4
905              9      11      2
767              5       4      2
72               9      11      2
908              1       7      2
235              9       8     11
37               2       9      0

[811 rows x 3 columns]

In [429]:
y_train

479      4
47       8
529      1
647      3
19       1
725      6
783      3
341      3
686     11
679     11
629      2
592     10
836      4
932     10
364      9
177      9
644     12
60       5
788     11
913      7
304     12
922     13
673      0
773      1
107      4
759      6
1002    11
587      5
819      4
99      10
        ..
398      9
925      9
668      4
490     10
252     10
907     11
468      5
914      8
357      2
254     11
276     13
178      1
281      5
390     11
508     12
749      3
583      4
972      4
129      0
144      1
960      1
847     10
645     11
715      3
905     13
767      1
72      13
908      9
235     10
37       4
Name: DESTINATION, Length: 811, dtype: int64

In [409]:
#applying model

#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 3)
knn


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [430]:
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)
cv_scores

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [431]:
cv_scores.mean()

1.0

In [432]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)

predictions_test

array([ 3,  9, 13, 10,  4,  0,  9,  4, 11, 12,  2, 11,  1,  7,  0, 10,  1,
       11,  1, 11,  7,  8,  5,  0,  6,  2, 11, 13, 13,  8, 11,  1,  1,  0,
        1,  8,  0,  7,  9,  2,  2,  4,  4, 11,  5,  6,  1,  9,  7,  4,  6,
        2,  4,  3,  7, 10,  3,  1,  7, 12,  4, 11,  2, 12,  6, 11,  4,  1,
       13,  2,  4,  2, 11, 13,  4, 10,  3,  1, 11, 13,  6, 11, 11,  1, 11,
        0,  8,  5, 13,  4,  8, 10,  1, 13,  1,  3,  1,  9,  2,  3,  4,  8,
        2,  4,  5, 10,  7,  7,  8, 11,  1,  2,  7,  1, 12,  4,  1,  7,  3,
       11,  1, 11,  4,  1,  3,  1, 11,  8, 13, 12, 13,  4, 12,  1, 12,  9,
       13,  8,  8, 10,  4, 12, 12,  3,  5,  4,  8, 12,  7, 11,  9, 10,  1,
       11,  4,  4,  2,  5,  4, 11,  7, 11, 11, 11,  3,  2,  0, 10,  4,  0,
       10, 11,  8,  2, 11,  1, 12,  7,  9,  0,  7,  4, 11, 11, 11, 12,  9,
       10,  9,  9,  8,  8, 11, 12, 12,  2,  3,  1, 12,  4,  3,  0,  1])

In [433]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 30  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11]]


In [434]:
#finding accuracy of training data

from sklearn import metrics

knn.fit(X_train,y_train)
predictions_train = knn.predict(X_train)

predictions_train

#finding accuracy of training data
print('Accuracy is',metrics.accuracy_score(y_train,predictions_train))

Accuracy is 1.0


In [435]:
#finding accuracy of tresting data
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 1.0


In [436]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        25
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        12
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       1.00      1.00      1.00        11
          11       1.00      1.00      1.00        30
          12       1.00      1.00      1.00        15
          13       1.00      1.00      1.00        11

   micro avg       1.00      1.00      1.00       203
   macro avg       1.00      1.00      1.00       203
weighted avg       1.00      1.00      1.00       203



In [437]:
from sklearn.naive_bayes import GaussianNB

In [438]:
#Create a Gaussian Classifier
gau = GaussianNB()

cvscores_gau = cross_val_score(gau,features_data,prediction_class,cv=10)
cvscores_gau

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [439]:
cvscores_gau.mean()

1.0

In [440]:
# Train the model using the training sets
gau.fit(X_train,y_train)

#Predict Output
prediction_gau = gau.predict(X_test) # 0:Overcast, 2:Mild

In [441]:
prediction_gau

array([ 3,  9, 13, 10,  4,  0,  9,  4, 11, 12,  2, 11,  1,  7,  0, 10,  1,
       11,  1, 11,  7,  8,  5,  0,  6,  2, 11, 13, 13,  8, 11,  1,  1,  0,
        1,  8,  0,  7,  9,  2,  2,  4,  4, 11,  5,  6,  1,  9,  7,  4,  6,
        2,  4,  3,  7, 10,  3,  1,  7, 12,  4, 11,  2, 12,  6, 11,  4,  1,
       13,  2,  4,  2, 11, 13,  4, 10,  3,  1, 11, 13,  6, 11, 11,  1, 11,
        0,  8,  5, 13,  4,  8, 10,  1, 13,  1,  3,  1,  9,  2,  3,  4,  8,
        2,  4,  5, 10,  7,  7,  8, 11,  1,  2,  7,  1, 12,  4,  1,  7,  3,
       11,  1, 11,  4,  1,  3,  1, 11,  8, 13, 12, 13,  4, 12,  1, 12,  9,
       13,  8,  8, 10,  4, 12, 12,  3,  5,  4,  8, 12,  7, 11,  9, 10,  1,
       11,  4,  4,  2,  5,  4, 11,  7, 11, 11, 11,  3,  2,  0, 10,  4,  0,
       10, 11,  8,  2, 11,  1, 12,  7,  9,  0,  7,  4, 11, 11, 11, 12,  9,
       10,  9,  9,  8,  8, 11, 12, 12,  2,  3,  1, 12,  4,  3,  0,  1])

In [442]:
print(confusion_matrix(y_test,prediction_gau))

[[10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 30  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11]]


In [443]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,prediction_gau))

Accuracy is 1.0


In [444]:
print(classification_report(y_test,prediction_gau))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        25
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00        12
           4       1.00      1.00      1.00        24
           5       1.00      1.00      1.00         6
           6       1.00      1.00      1.00         5
           7       1.00      1.00      1.00        14
           8       1.00      1.00      1.00        14
           9       1.00      1.00      1.00        11
          10       1.00      1.00      1.00        11
          11       1.00      1.00      1.00        30
          12       1.00      1.00      1.00        15
          13       1.00      1.00      1.00        11

   micro avg       1.00      1.00      1.00       203
   macro avg       1.00      1.00      1.00       203
weighted avg       1.00      1.00      1.00       203



In [446]:
from sklearn import tree

dec = tree.DecisionTreeClassifier()

dec


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [447]:
cv_scores_dec = cross_val_score(dec,features_data,prediction_class,cv=10)
cv_scores_dec

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [448]:
cv_scores_dec.mean()

1.0

In [449]:
dec.fit(X_train, y_train)

prediction_dec = dec.predict(X_test)
prediction_dec

array([ 3,  9, 13, 10,  4,  0,  9,  4, 11, 12,  2, 11,  1,  7,  0, 10,  1,
       11,  1, 11,  7,  8,  5,  0,  6,  2, 11, 13, 13,  8, 11,  1,  1,  0,
        1,  8,  0,  7,  9,  2,  2,  4,  4, 11,  5,  6,  1,  9,  7,  4,  6,
        2,  4,  3,  7, 10,  3,  1,  7, 12,  4, 11,  2, 12,  6, 11,  4,  1,
       13,  2,  4,  2, 11, 13,  4, 10,  3,  1, 11, 13,  6, 11, 11,  1, 11,
        0,  8,  5, 13,  4,  8, 10,  1, 13,  1,  3,  1,  9,  2,  3,  4,  8,
        2,  4,  5, 10,  7,  7,  8, 11,  1,  2,  7,  1, 12,  4,  1,  7,  3,
       11,  1, 11,  4,  1,  3,  1, 11,  8, 13, 12, 13,  4, 12,  1, 12,  9,
       13,  8,  8, 10,  4, 12, 12,  3,  5,  4,  8, 12,  7, 11,  9, 10,  1,
       11,  4,  4,  2,  5,  4, 11,  7, 11, 11, 11,  3,  2,  0, 10,  4,  0,
       10, 11,  8,  2, 11,  1, 12,  7,  9,  0,  7,  4, 11, 11, 11, 12,  9,
       10,  9,  9,  8,  8, 11, 12, 12,  2,  3,  1, 12,  4,  3,  0,  1])

In [450]:
from sklearn.metrics import accuracy_score

#confusion matrix

print(confusion_matrix(y_test,prediction_dec))

[[10  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 25  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 12  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 24  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 14  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 11  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 30  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 11]]


In [451]:
#accuracy

print("Accuracy is " ,metrics.accuracy_score(y_test,prediction_dec))

Accuracy is  1.0


In [471]:
#giving input 
new=pd.DataFrame([[6,1,3]])
new

0  1  2
0  6  1  3

In [472]:
testknn = knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(test)


2

In [473]:
pre_out_knn = arr[int(testknn)]

In [474]:
print(pre_out_knn)

Idukki


In [475]:
testgau = knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(test)

2

In [476]:
pre_out_gau = arr[int(testgau)]

In [477]:
print(pre_out_gau)

Idukki


In [478]:
testdec = knn.predict(new)
arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
int(test)

2

In [479]:
pre_out_dec = arr[int(testdec)]

In [480]:
print(pre_out_dec)

Idukki
