In [126]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv("medscon.csv")
type(data)

pandas.core.frame.DataFrame

In [127]:
data

GENERIC NAME         CONDITION              SOURCE  COUNT
0           minocycline              Acne           Ernakulam  987.0
1            sertraline        Depression           Kozhikode  365.0
2            lisinopril      Hypertension            Kasargod   54.0
3          elvitegravir          AIDS/HIV            Palakkad   32.0
4         triamcinolone         Hair Loss  Thiruvananthapuram   65.0
5     lidocaine topical  Gastrointestinal      Pathanamthitta   65.0
6         emtricitabine          AIDS/HIV             Aleppey  789.0
7            lisinopril      Hypertension            Kasargod    5.0
8             bupropion        Depression  Thiruvananthapuram  654.0
9       diphenhydramine              Cold           Kozhikode  320.0
10    minoxidil topical         Hair Loss              Kollam  654.0
11       spironolactone              Acne  Thiruvananthapuram  500.0
12            alvimopan  Gastrointestinal            Kottayam  741.0
13           sertraline        Depression           Kozhikode   65.0
14     chlorpheniramine              Cold            Kasargod  654.0
15        triamcinolone         Hair Loss  Thiruvananthapuram  654.0
16         elvitegravir          AIDS/HIV            Palakkad  797.0
17    lidocaine topical  Gastrointestinal      Pathanamthitta   32.0
18           duloxetine        Depression              Kollam   65.0
19    minoxidil topical         Hair Loss              Kollam    6.0
20        emtricitabine          AIDS/HIV             Aleppey  987.0
21           lisinopril      Hypertension            Kasargod    6.0
22    minoxidil topical         Hair Loss              Kollam  654.0
23            bupropion        Depression  Thiruvananthapuram   32.0
24       spironolactone              Acne  Thiruvananthapuram  125.0
25          rizatriptan          Migraine            Palakkad  654.0
26         elvitegravir          AIDS/HIV            Palakkad   25.0
27            alvimopan  Gastrointestinal            Kottayam   98.0
28     chlorpheniramine              Cold            Kasargod   32.0
29          rizatriptan          Migraine            Palakkad   65.0
...                 ...               ...                 ...    ...
6006          darunavir          AIDS/HIV            Thrissur   21.0
6007         sertraline        Depression           Kozhikode   65.0
6008  lidocaine viscous  Gastrointestinal            Thrissur   77.0
6009        doxycycline              Acne      Pathanamthitta  789.0
6010        sumatriptan          Migraine          Malappuram  987.0
6011      emtricitabine          AIDS/HIV             Aleppey   21.0
6012         eletriptan          Migraine             Wayanad    5.0
6013   chlorpheniramine              Cold            Kasargod   34.0
6014        doxycycline              Acne      Pathanamthitta  658.0
6015  lidocaine viscous  Gastrointestinal            Thrissur   65.0
6016    diphenhydramine              Cold           Kozhikode   32.0
6017  lidocaine viscous  Gastrointestinal            Thrissur  340.0
6018          darunavir          AIDS/HIV            Thrissur   21.0
6019         lisinopril      Hypertension            Kasargod  645.0
6020          bupropion        Depression  Thiruvananthapuram   52.0
6021        sumatriptan          Migraine          Malappuram    5.0
6022          darunavir          AIDS/HIV            Thrissur   32.0
6023  lidocaine viscous  Gastrointestinal            Thrissur  972.0
6024    diphenhydramine              Cold           Kozhikode   32.0
6025          bupropion        Depression  Thiruvananthapuram   65.0
6026        doxycycline              Acne      Pathanamthitta   45.0
6027         lisinopril      Hypertension            Kasargod   31.0
6028    diphenhydramine              Cold           Kozhikode   32.0
6029          bupropion        Depression  Thiruvananthapuram   64.0
6030        doxycycline              Acne      Pathanamthitta   12.0
6031  lidocaine viscous  Gastrointestinal            Thrissur  621.0
6032     

In [128]:
#preprocessing of data

from sklearn.preprocessing import LabelEncoder
processed_data = pd.DataFrame()

#Label Encoder converts into numerical value

lb_make = LabelEncoder()
processed_data["GENERIC NAME"] = lb_make.fit_transform(data["GENERIC NAME"])
#processed_data["GENERIC"] = data["GENERIC NAME"]
processed_data["CONDITION"] = lb_make.fit_transform(data["CONDITION"])
#processed_data["CONDITIO"] = data["CONDITION"]
processed_data["SOURCE"] = lb_make.fit_transform(data["SOURCE"])
#processed_data["src"] = data["SOURCE"]
#processed_data["cnt"] = data["COUNT"]
processed_data["COUNT"] = lb_make.fit_transform(data["COUNT"])

#processed_data["MONTH"] = lb_make.fit_transform(data["MONTH"])
#processed_data["Mon"] = data["MONTH"]
#processed_data["DESTINATION"] = lb_make.fit_transform(data["DESTINATION"])
#processed_data["DESTINATIO"] = data["DESTINATION"]

In [129]:
processed_data


#pd.set_option('display.height', 2400)
#pd.set_option('display.max_rows', 2400)

GENERIC NAME  CONDITION  SOURCE  COUNT
0               15          1       1    112
1               18          3       7     68
2               13          6       4     30
3                9          0       9     20
4               22          5      11     38
5               11          4      10     38
6               10          0       0    102
7               13          6       4      2
8                1          3      11     92
9                5          2       7     58
10              16          5       5     92
11              19          1      11     76
12               0          4       6     99
13              18          3       7     38
14               2          2       4     92
15              22          5      11     92
16               9          0       9    103
17              11          4      10     20
18               7          3       5     38
19              16          5       5      3
20              10          0       0    112
21              13          6       4      3
22              16          5       5     92
23               1          3      11     20
24              19          1      11     50
25              17          7       9     92
26               9          0       9     17
27               0          4       6     46
28               2          2       4     20
29              17          7       9     38
...            ...        ...     ...    ...
6006             4          0      12     13
6007            18          3       7     38
6008            12          4      12     44
6009             6          1      10    102
6010            20          7       8    112
6011            10          0       0     13
6012             8          7      13      2
6013             2          2       4     21
6014             6          1      10     95
6015            12          4      12     38
6016             5          2       7     20
6017            12          4      12     63
6018             4          0      12     13
6019            13          6       4     88
6020             1          3      11     29
6021            20          7       8      2
6022             4          0      12     20
6023            12          4      12    109
6024             5          2       7     20
6025             1          3      11     38
6026             6          1      10     26
6027            13          6       4     19
6028             5          2       7     20
6029             1          3      11     37
6030             6          1      10      8
6031            12          4      12     87
6032             4          0      12     20
6033             8          7      13      6
6034            13          6       2     88
6035             5          2       3     20

[6036 rows x 4 columns]

In [130]:
# to extract the features

#printing the columns

features = processed_data.columns
print(features)

Index(['GENERIC NAME', 'CONDITION', 'SOURCE', 'COUNT'], dtype='object')


In [131]:
#printing the last column which is used to predict 

predict_class = data.columns[-1]
predict_class

'COUNT'

In [132]:
#print the value to be predicted

predictions = data[predict_class]
predictions

0       987.0
1       365.0
2        54.0
3        32.0
4        65.0
5        65.0
6       789.0
7         5.0
8       654.0
9       320.0
10      654.0
11      500.0
12      741.0
13       65.0
14      654.0
15      654.0
16      797.0
17       32.0
18       65.0
19        6.0
20      987.0
21        6.0
22      654.0
23       32.0
24      125.0
25      654.0
26       25.0
27       98.0
28       32.0
29       65.0
        ...  
6006     21.0
6007     65.0
6008     77.0
6009    789.0
6010    987.0
6011     21.0
6012      5.0
6013     34.0
6014    658.0
6015     65.0
6016     32.0
6017    340.0
6018     21.0
6019    645.0
6020     52.0
6021      5.0
6022     32.0
6023    972.0
6024     32.0
6025     65.0
6026     45.0
6027     31.0
6028     32.0
6029     64.0
6030     12.0
6031    621.0
6032     32.0
6033     10.0
6034    645.0
6035     32.0
Name: COUNT, Length: 6036, dtype: float64

In [133]:
#printing the numerical values of DESTINATION to be predicted

prediction_class = processed_data["COUNT"]
prediction_class

0       112
1        68
2        30
3        20
4        38
5        38
6       102
7         2
8        92
9        58
10       92
11       76
12       99
13       38
14       92
15       92
16      103
17       20
18       38
19        3
20      112
21        3
22       92
23       20
24       50
25       92
26       17
27       46
28       20
29       38
       ... 
6006     13
6007     38
6008     44
6009    102
6010    112
6011     13
6012      2
6013     21
6014     95
6015     38
6016     20
6017     63
6018     13
6019     88
6020     29
6021      2
6022     20
6023    109
6024     20
6025     38
6026     26
6027     19
6028     20
6029     37
6030      8
6031     87
6032     20
6033      6
6034     88
6035     20
Name: COUNT, Length: 6036, dtype: int64

In [134]:
features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]

#    features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE","MONTH"]]

#features_data = processed_data[["GENERIC NAME","CONDITION","SOURCE"]]
features_data

GENERIC NAME  CONDITION  SOURCE
0               15          1       1
1               18          3       7
2               13          6       4
3                9          0       9
4               22          5      11
5               11          4      10
6               10          0       0
7               13          6       4
8                1          3      11
9                5          2       7
10              16          5       5
11              19          1      11
12               0          4       6
13              18          3       7
14               2          2       4
15              22          5      11
16               9          0       9
17              11          4      10
18               7          3       5
19              16          5       5
20              10          0       0
21              13          6       4
22              16          5       5
23               1          3      11
24              19          1      11
25              17          7       9
26               9          0       9
27               0          4       6
28               2          2       4
29              17          7       9
...            ...        ...     ...
6006             4          0      12
6007            18          3       7
6008            12          4      12
6009             6          1      10
6010            20          7       8
6011            10          0       0
6012             8          7      13
6013             2          2       4
6014             6          1      10
6015            12          4      12
6016             5          2       7
6017            12          4      12
6018             4          0      12
6019            13          6       4
6020             1          3      11
6021            20          7       8
6022             4          0      12
6023            12          4      12
6024             5          2       7
6025             1          3      11
6026             6          1      10
6027            13          6       4
6028             5          2       7
6029             1          3      11
6030             6          1      10
6031            12          4      12
6032             4          0      12
6033             8          7      13
6034            13          6       2
6035             5          2       3

[6036 rows x 3 columns]

In [135]:
#training

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features_data,prediction_class,train_size = 0.80,test_size=0.20,random_state = 1)

np.random.seed(0) #to make random numbers predictable

# Show the results of the split
#print "Training set has {} samples.".format(X_train.shape[0])
#print "Testing set has {} samples.".format(X_test.shape[0])

#print(X_train.shape, y_train.shape) 
#print(X_test.shape, y_test.shape) 

print("Training samples")
print(X_train.shape[0])
#print(y_train.shape[0])
print("Testing samples")
print(X_test.shape[0])


Training samples
4828
Testing samples
1208


In [136]:
X_train

GENERIC NAME  CONDITION  SOURCE
3778             8          7      13
5455             2          2       4
4892            11          4      10
4747             9          0       9
610             19          1      11
1859            11          4      10
3991             1          3      11
6031            12          4      12
560              2          2       4
3780             9          0       9
3100            15          1       1
717              7          3       5
1540             8          7      13
4251            20          7       8
2054            13          6       4
4875             3          1       0
5872             4          0      12
3339             5          2       7
3636            22          5      11
1828            21          1      12
4408            16          5       5
3791            13          6       4
1796            20          7       8
5702            17          7       9
1683             7          3       5
4625             1          3      11
2209            17          7       9
100             16          5       5
4364             8          7      13
5275             9          0       9
...            ...        ...     ...
1031             9          0       9
1110             2          2       4
1888             5          2       7
3550            17          7       9
1527             7          3       5
753              0          4       6
3049             8          7      13
2628            11          4      10
562              2          2       4
4764            20          7       8
3562             9          0       9
252             16          5       5
2516            13          6       4
2962            10          0       0
4453            21          1      12
5374             1          3      11
5396            18          3       7
1202            17          7       9
3462             5          2       7
2797            16          5       5
4225            19          1      11
144             19          1      11
5056             9          0       9
2895            10          0       0
2763             5          2       7
905             14          6       8
5192             7          3       5
3980             4          0      12
235              0          4       6
5157            15          1       1

[4828 rows x 3 columns]

In [137]:
y_train

3778     29
5455     13
4892     92
4747     13
610     107
1859     38
3991     38
6031     87
560      20
3780    112
3100     82
717      38
1540     30
4251      2
2054      2
4875     72
5872     59
3339     20
3636     30
1828    112
4408     13
3791     90
1796     31
5702     38
1683     20
4625     38
2209      3
100      18
4364      2
5275     84
       ... 
1031     17
1110     59
1888     59
3550     38
1527     38
753      57
3049     30
2628      3
562      13
4764     38
3562     85
252      81
2516     30
2962     38
4453     42
5374     38
5396     20
1202      3
3462     35
2797     38
4225     30
144     100
5056     17
2895     13
2763     20
905       3
5192     38
3980     51
235       3
5157     97
Name: COUNT, Length: 4828, dtype: int64

In [153]:
#applying model

#fitting into KNN

from sklearn import neighbors
from sklearn.model_selection import cross_val_score

knn = neighbors.KNeighborsClassifier(n_neighbors = 25)
knn


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=25, p=2,
           weights='uniform')

In [154]:
cv_scores = cross_val_score(knn, features_data, prediction_class, cv = 10)
cv_scores

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


array([ 0.19765739,  0.19555556,  0.19275124,  0.21911038,  0.21938776,
        0.22959184,  0.21913043,  0.24      ,  0.228471  ,  0.22671353])

In [155]:
cv_scores.mean()

0.2168369124793737

In [141]:
#printing confusion matrix

knn.fit(X_train,y_train)
predictions_test = knn.predict(X_test)

predictions_test

array([30, 20, 13, ..., 38, 20, 20])

In [142]:
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix  

# Model Accuracy: how often is the classifier correct?
print(confusion_matrix(y_test,predictions_test))

[[ 0  0  4 ...,  0  0  0]
 [ 0  0  0 ...,  0  0  0]
 [ 0  0 38 ...,  0  0  0]
 ..., 
 [ 0  0  0 ...,  0  0  0]
 [ 0  0  0 ...,  0  0  0]
 [ 0  0  0 ...,  0  0  0]]


In [143]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,predictions_test))

Accuracy is 0.163079470199


In [101]:
print(classification_report(y_test,predictions_test))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.00      0.00      0.00         2
           2       0.24      0.41      0.30        29
           3       0.15      0.33      0.21        27
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00        10
           9       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         2
          13       0.09      0.53      0.15        17
          15       0.00      0.00      0.00         6
          16       0.00      0.00      0.00         2
          17       0.00      0.00      0.00         6
          18       0.00      0.00      0.00         1
          19       0.09    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [102]:
from sklearn.naive_bayes import GaussianNB

In [103]:
#Create a Gaussian Classifier
gau = GaussianNB()

cvscores_gau = cross_val_score(gau,features_data,prediction_class,cv=10)
cvscores_gau

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


array([ 0.07344633,  0.07714286,  0.06646526,  0.0694864 ,  0.07076923,
        0.06769231,  0.0155642 ,  0.02723735,  0.01639344,  0.02868852])

In [104]:
cvscores_gau.mean()

0.051288590855277962

In [105]:
# Train the model using the training sets
gau.fit(X_train,y_train)

#Predict Output
prediction_gau = gau.predict(X_test) # 0:Overcast, 2:Mild

In [106]:
prediction_gau

array([113,  74, 110,  23,  54,  43,  36,  54,  23,  74,  36,  43,  36,
        23,   9,   9,  52,  79,  23, 110,  36,  82,  60,  44,  52,  14,
        40,  10,  20,  33,  86,  43,   1, 110,  14,  44,  33,  22,  22,
        22,  83,  14,  51,  54,  52,  10,  22,  10,  93,  52,  54,  14,
        22,  10,  79,  44, 110,  10, 113,  36,  60,  44,  33,  33,   1,
        82,  54,  44,  83,  14,  83,  14,  43,  40,  82,  22, 110,   9,
        82, 110, 113,   9,  60,   1,   1,  22,  54,  23,  54,   9,  36,
        79,  83,  83,  54,  60,  33,  86,  43,  93,  86,  22,  51,  60,
        44,  40,  22,  54,  83,  86,   1,  60,  33,  22,  14,  79,  44,
        36,  54, 113,  86,  51,   1,  23,  14,  33,  33,   1,  51,   1,
        43,  10, 113,  33,  83,  86,  74, 113,  86,  83,   1,  36,  52,
       110,  54,  79,  33,  10,  22,  52,  23,  43,  10,  43,  52,   1,
        40,  33,   1,   1,  86,  83,  93,   1,  14,  43,  10,  43,  43,
        86,  36,  40,  43,  82,  40,  10,  86,  83,  43,  14,   

In [107]:
print(confusion_matrix(y_test,prediction_gau))

[[0 2 0 ..., 0 0 0]
 [0 2 0 ..., 0 0 0]
 [0 2 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [108]:
#finding accuracy
print('Accuracy is',metrics.accuracy_score(y_test,prediction_gau))

Accuracy is 0.0331125827815


In [109]:
print(classification_report(y_test,prediction_gau))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.06      1.00      0.11         2
           2       0.00      0.00      0.00        29
           3       0.00      0.00      0.00        27
           4       0.00      0.00      0.00         9
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00        10
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.00      0.00      0.00         2
          12       0.00      0.00      0.00         2
          13       0.00      0.00      0.00        17
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         6
          16       0.00      0.00      0.00         2
          17       0.00    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1145: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [110]:
from sklearn import tree

dec = tree.DecisionTreeClassifier()

dec


DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [111]:
cv_scores_dec = cross_val_score(dec,features_data,prediction_class,cv=10)
cv_scores_dec

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:652: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=10.
  % (min_groups, self.n_splits)), Warning)


array([ 0.1920904 ,  0.21142857,  0.20241692,  0.20543807,  0.20307692,
        0.20923077,  0.27237354,  0.25680934,  0.26229508,  0.2704918 ])

In [112]:
cv_scores_dec.mean()

0.22856514087340832

In [113]:
dec.fit(X_train, y_train)

prediction_dec = dec.predict(X_test)
prediction_dec

array([106,   8,  38,  38,  38,  38,  38,  38,  38,   8,  38,  38,  38,
        38,  20,  20,  13,  37,  38,  38,  38, 102,  20,  38,  13,  38,
        92,  11,  20,  42,  38,  38,  13,  38,  38,  38,  42,  20,  20,
        20,   3,  38,  20,  38,  13,  11,  20,  11,  38,  13,  38,  38,
        20,  11,  37,  38,  38,  11, 106,  38,  20,  38,  42,  42,  13,
       102,  38,  38,   3,  38,   3,  38,  38,  92, 102,  20,  38,  20,
       102,  38, 106,  20,  20,  13,  13,  20,  38,  38,  38,  20,  38,
        37,   3,   3,  38,  20,  42,  38,  38,  38,  38,  20,  20,  20,
        38,  92,  20,  38,   3,  38,  13,  20,  42,  20,  38,  37,  38,
        38,  38, 106,  38,  20,  13,  38,  38,  42,  42,  13,  20,  13,
        38,  11, 106,  42,   3,  38,   8, 106,  38,   3,  13,  38,  13,
        38,  38,  37,  42,  11,  20,  13,  38,  38,  11,  38,  13,  13,
        92,  42,  13,  13,  38,   3,  38,  13,  38,  38,  11,  38,  38,
        38,  38,  92,  38, 102,  92,  11,  38,   3,  38,  38,  1

In [114]:
from sklearn.metrics import accuracy_score

#confusion matrix

print(confusion_matrix(y_test,prediction_dec))

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [115]:
#accuracy

print("Accuracy is " ,metrics.accuracy_score(y_test,prediction_dec))

Accuracy is  0.248344370861


In [116]:
#giving input 
new=pd.DataFrame([[15,1,1]])
new

0  1  2
0  15  1  1

In [79]:
#test=knn.predict(new)
#arr=["Aleppey","Ernakulam","Idukki","Kannur","Kasarkode","Kollam","Kottayam","Kozhikode","Malappuram","Palakkad","Pathanamthitta","Thiruvananthapuram","Thrissur","Wayanad"];
#int(test)
pre_out = knn.predict(new)

In [45]:
pre_out = knn.predict(new)

ValueError: query data dimension must match training data dimension

In [ ]:
pre_out_knn =arr[int(test)]

In [38]:
print(pre_out_knn)

Kannur


In [39]:
pre_out_gau = gau.predict(new)

In [40]:
print(pre_out_gau)

[2]


In [41]:
pre_out_dec = dec.predict(new)

In [42]:
print(pre_out_dec)

[13]
